syntax = "proto3";

package proto;

import "public.proto";

message ActivityStorySettleReq {
    uint32 ActivityId = 1;
    repeated ActivityStorySettle List = 2;
    Events Events = 14;
    repeated uint32 Evidences = 15;
    bytes NextPackage = 2047;
}

message ActivityStorySettle {
    uint32 StoryId = 1;
    repeated ActivityStoryOptions Major = 2;
    repeated ActivityStoryOptions Personality = 3;
    bytes NextPackage = 2047;
}

message ActivityStoryOptions {
    uint32 Group = 1;
    uint32 Choice = 2;
    uint32 Factor = 3;
    bytes NextPackage = 2047;
}
