syntax = "proto3";

package proto;

import "public.proto";

message GachaSpinReq {
    uint32 Id = 1;
    uint32 Mode = 2;
    repeated ItemTpl Check = 15;
    bytes NextPackage = 2047;
}

message GachaSpinResp {
    repeated GachaCard Cards = 1;
    ChangeInfo Change = 2;
    int64 Time = 3;
    uint32 AMissTimes = 10;
    uint32 GachaTotalTimes = 11;
    uint32 TotalTimes = 12;
    uint32 AupGuaranteeTimes = 13;
    uint32 AupMissTimes = 14;
    uint32 DaysCount = 15;
    bytes NextPackage = 2047;
}

message GachaCard {
    ItemTpl Card = 1;
    repeated ItemTpl Rewards = 2;
    bytes NextPackage = 2047;
}

message GachaSpinSyncResp {
    repeated Res Res = 2;
    repeated Item Items = 3;
    bytes NextPackage = 2047;
}
