syntax = "proto3";

package ServerProto;

message CharacterChat {
    uint32 id = 2;
    uint32 process = 3;
    bool end = 4;
    repeated uint32 options = 5;
}

message CharacterGemPreset {
    string name = 2;
    repeated uint32 gems = 3;
}

message CharacterGem {
    bool locked = 2;
    repeated uint32 attributes = 3;
    repeated uint32 overlock = 4;
    repeated uint32 alterAttributes = 5;
    repeated uint32 alterOverlock = 6;
}

message CharacterGemSlot {
    uint32 id = 2;
    repeated CharacterGem gems = 3;
}

message CharacterContact {
    map<int32, CharacterChat> chats = 2;
    bool top = 3;
    uint64 triggerTime = 4;
}

message CharacterInfo {
    int64 createTime = 2;
    uint32 charId = 3;
    uint32 level = 4;
    uint32 exp = 5;
    uint32 advance = 6;
    uint32 rank = 7;
    bool favorite = 8;
    uint32 affinityLevel = 9; //好感
    uint32 affinityExp = 10;
    uint32 skin = 11;
    repeated uint32 skills = 12;
    bytes talents = 13;
    repeated uint32 plots = 14;
    uint32 gemPresetIndex = 15;
    repeated CharacterGemPreset gemPresets = 16;
    repeated CharacterGemSlot gemSlots = 17;
    CharacterContact contact = 18;
}

message CharacterCompBin {
    repeated CharacterInfo charInfoList = 2;
    repeated GameDiscInfoBin gameDiscList = 4;
}

message QuestProgressBin {
    uint32 cur = 1;
    uint32 max = 2;
}

message QuestInfoBin {
    uint32 id = 1;
    uint32 type = 2;
    uint32 status = 3;
    int64 expire = 4;
    repeated QuestProgressBin progress = 15;
}

message QuestCompBin {
    repeated QuestInfoBin quests = 1;
    bool firstLoginNotifyDone = 2;
}

message PlayerBasicCompBin {
    // int32 uid = 1;

    // Details
    int64 createTime = 2;         // 创建时间
    string name = 3;
    string signature = 4;
    bool gender = 5;
    int32 headIcon = 6;
    int32 skinId = 7;
    int32 titlePrefix = 8;
    int32 titleSuffix = 9;
    int64 music = 10;
    repeated int32 honor = 11;
    repeated int32 showChars = 12;
    repeated int32 boards = 13;
    int32 level = 14;
    int32 exp = 15;
    int32 energy = 16;
    int64 energyLastUpdate = 17;  // 体力上次恢复时间
    int32 signInIndex = 18;
    int64 lastEpochDay = 19;       // 上次纪元日（用于每日重置）
    int64 lastLogin = 20;          // 上次登录时间
}

message PlayerSaveData {
    // int32 uid = 1;

    PlayerBasicCompBin playerdata = 2;
    CharacterCompBin charComp = 3;
    QuestCompBin questComp = 4;
}

message GameDiscInfoBin {
    //private transient DiscDef data;
    //private transient Player player;
    
    int32 discId = 2;
    int32 level = 3;
    int32 exp = 4;
    int32 phase = 5;
    int32 star = 6;
    
    bool read = 7;
    bool avg = 8;
    
    int64 createTime = 9;
}
