syntax = "proto3";

package ServerProto;

message CharacterChat {
    uint32 id = 2;
    uint32 process = 3;
    bool end = 4;
    repeated uint32 options = 5;
}

message CharacterGemPreset {
    string name = 2;
    repeated uint32 gems = 3;
}

message CharacterGem {
    bool locked = 2;
    repeated uint32 attributes = 3;
    repeated uint32 overlock = 4;
    repeated uint32 alterAttributes = 5;
    repeated uint32 alterOverlock = 6;
}

message CharacterGemSlot {
    uint32 id = 2;
    repeated CharacterGem gems = 3;
}

message CharacterContact {
    map<int32, CharacterChat> chats = 2;
    bool top = 3;
    uint64 triggerTime = 4;
}

message CharacterInfo {
    int64 createTime = 2;
    uint32 charId = 3;
    uint32 level = 4;
    uint32 exp = 5;
    uint32 advance = 6;
    uint32 rank = 7;
    bool favorite = 8;
    uint32 affinityLevel = 9; //好感
    uint32 affinityExp = 10;
    uint32 skin = 11;
    repeated uint32 skills = 12;
    bytes talents = 13;
    repeated uint32 plots = 14;
    uint32 gemPresetIndex = 15;
    repeated CharacterGemPreset gemPresets = 16;
    repeated CharacterGemSlot gemSlots = 17;
    CharacterContact contact = 18;
}

message CharacterCompBin {
    repeated CharacterInfo charInfoList = 2;
    repeated GameDiscInfoBin gameDiscList = 4;
}

message QuestProgressBin {
    uint32 cur = 1;
    uint32 max = 2;
}

message QuestInfoBin {
    uint32 id = 1;
    uint32 type = 2;
    uint32 status = 3;
    int64 expire = 4;
    uint32 condition = 5;
    uint32 param = 6;
    repeated QuestProgressBin progress = 15;
}

message QuestCompBin {
    repeated QuestInfoBin quests = 1;
    bool firstLoginNotifyDone = 2;
    repeated uint32 dailyActiveIds = 3;
    repeated uint32 weeklyActiveIds = 4;
    bool dailyShopRewardClaimed = 5;
    bool dailyMallRewardClaimed = 6;
}

message BattlePassCompBin {
    uint32 battlePassId = 1;
    uint32 mode = 2;
    uint32 level = 3;
    uint32 exp = 4;
    uint32 expWeek = 5;
    bytes basicReward = 6;
    bytes premiumReward = 7;
    repeated QuestInfoBin quests = 8;
}

message AchievementInfoBin {
    uint32 id = 1;
    uint32 status = 2;
    int64 completed = 3;
    bool claimed = 4;
    repeated QuestProgressBin progress = 5;
}

message AchievementCompBin {
    repeated AchievementInfoBin achievements = 1;
}

message InventoryCompBin {
    map<uint32, int64> items = 1;
    map<uint32, int64> resources = 2;
    repeated uint32 skins = 3;
    repeated uint32 headIcons = 4;
    repeated uint32 titles = 5;
    repeated uint32 honors = 6;
    map<uint32, uint32> shopBuyCount = 7;
    map<string, uint32> mallBuyCount = 8;
    map<string, uint32> mallPackageBuyCount = 9;
    map<string, uint32> gemMaidenClaimed = 10;
    map<string, uint32> monthlyCardBuyCount = 11;
}

message MailAttachmentBin {
    uint32 tid = 1;
    int64 qty = 2;
}

message MailInfoBin {
    uint32 id = 1;
    string subject = 2;
    string desc = 3;
    string author = 4;
    int64 time = 5;
    int64 deadline = 6;
    bool read = 7;
    bool recv = 8;
    bool pin = 9;
    uint64 flag = 10;
    repeated MailAttachmentBin attachments = 11;
}

message MailCompBin {
    uint32 nextMailId = 1;
    repeated MailInfoBin mails = 2;
    bool welcomeMailCreated = 3;
}

message GachaBannerInfoBin {
    uint32 id = 1;
    uint32 total = 2;
    bool usedFirstTen = 3;
    bool usedGuarantee = 4;
}

message GachaPityStateBin {
    uint32 missTimesA = 1;
    uint32 missTimesUpA = 2;
    uint32 missTimesB = 3;
    bool bGuaranteeDebt = 4;
}

message GachaCardGroupBin {
    repeated uint32 cards = 1;
}

message NewbieGachaStateBin {
    uint32 id = 1;
    uint32 remainingSpinCount = 2;
    uint32 saveCount = 3;
    int32 selectedResult = 4;
    bool received = 5;
    repeated uint32 pendingResult = 6;
    repeated GachaCardGroupBin savedResults = 7;
}

message GachaHistoryBin {
    uint32 storageId = 1;
    uint32 gachaId = 2;
    int64 time = 3;
    repeated uint32 ids = 4;
}

message GachaCompBin {
    map<uint32, GachaBannerInfoBin> banners = 1;
    map<uint32, GachaPityStateBin> pityStates = 2;
    map<uint32, NewbieGachaStateBin> newbieStates = 3;
    repeated GachaHistoryBin histories = 4;
}

message FormationInfoBin {
    uint32 number = 1;
    repeated uint32 charIds = 2;
    repeated uint32 discIds = 3;
    uint64 preselectionId = 4;
}

message FormationCompBin {
    repeated FormationInfoBin infos = 1;
}

message TowerPotentialLevelBin {
    uint32 id = 1;
    uint32 level = 2;
}

message TowerPresetCharBin {
    uint32 charId = 1;
    repeated TowerPotentialLevelBin potentials = 2;
}

message TowerPotentialPresetBin {
    uint64 uid = 1;
    string name = 2;
    bool preference = 3;
    int64 timestamp = 4;
    repeated TowerPresetCharBin chars = 5;
}

message TowerBuildBin {
    uint64 uid = 1;
    string name = 2;
    bool lock = 3;
    bool preference = 4;
    uint32 score = 5;
    repeated uint32 charIds = 6;
    repeated uint32 discIds = 7;
    map<uint32, uint32> charPotentials = 8;
    map<uint32, uint32> potentials = 9;
    map<uint32, int32> subNoteSkills = 10;
    repeated uint32 activeSecondaryIds = 11;
    uint32 towerId = 12;
}

message TowerShopGoodsBin {
    uint32 sid = 1;
    uint32 type = 2;
    uint32 idx = 3;
    uint32 goodsId = 4;
    int32 price = 5;
    int32 discount = 6;
    uint32 charPos = 7;
    bool sold = 8;
}

message TowerBattleCaseBin {
    uint32 subNoteDrops = 1;
    uint32 expReward = 2;
}

message TowerDoorCaseBin {
    uint32 floorNum = 1;
    uint32 roomType = 2;
}

message TowerPotentialCaseBin {
    uint32 teamLevel = 1;
    uint32 charId = 2;
    uint32 reroll = 3;
    uint32 rerollPrice = 4;
    bool strengthen = 5;
    bool rare = 6;
    repeated TowerPotentialLevelBin potentials = 7;
}

message TowerNpcEventCaseBin {
    uint32 npcId = 1;
    uint32 eventId = 2;
    repeated uint32 options = 3;
    bool completed = 4;
}

message TowerHawkerCaseBin {
    repeated TowerShopGoodsBin goods = 1;
    uint32 rerollTimes = 2;
    uint32 rerollPrice = 3;
}

message TowerStrengthenMachineCaseBin {
    bool free = 1;
    int32 discount = 2;
    uint32 times = 3;
}

message TowerRecoveryHPCaseBin {
    uint32 effectId = 1;
}

message TowerNpcRecoveryHPCaseBin {
    uint32 effectId = 1;
}

message TowerSyncHPCaseBin {
    bool placeholder = 1;
}

message TowerCaseBin {
    uint32 id = 1;
    uint32 type = 2;
    oneof data {
        TowerBattleCaseBin battleCase = 3;
        TowerDoorCaseBin doorCase = 4;
        TowerPotentialCaseBin potentialCase = 5;
        TowerNpcEventCaseBin npcEventCase = 6;
        TowerHawkerCaseBin hawkerCase = 7;
        TowerStrengthenMachineCaseBin strengthenMachineCase = 8;
        TowerRecoveryHPCaseBin recoveryHPCase = 9;
        TowerNpcRecoveryHPCaseBin npcRecoveryHPCase = 10;
        TowerSyncHPCaseBin syncHPCase = 11;
        TowerPotentialCaseBin selectSpecialPotentialCase = 12;
    }
}

message TowerRoomBin {
    uint32 stageId = 1;
    uint32 roomType = 2;
    uint32 mapId = 3;
    uint32 mapTableId = 4;
    string mapParam = 5;
    uint32 paramId = 6;
    uint32 lastCaseId = 7;
    bool hasDoor = 8;
    repeated TowerCaseBin cases = 9;
}

message TowerGameBin {
    uint32 towerId = 1;
    uint32 formationId = 2;
    uint64 buildId = 3;
    uint32 floorCount = 4;
    uint32 stageNum = 5;
    uint32 stageFloor = 6;
    uint32 teamLevel = 7;
    uint32 teamExp = 8;
    uint32 nextLevelExp = 9;
    int32 charHp = 10;
    uint32 battleTime = 11;
    repeated uint32 charIds = 12;
    repeated uint32 discIds = 13;
    uint32 pendingPotentialCases = 14;
    uint32 pendingRarePotentialCases = 15;
    bool completed = 16;
    bool sweep = 17;
    map<uint32, int32> items = 18;
    map<uint32, int32> res = 19;
    map<uint32, int32> potentials = 20;
    map<uint32, int32> rarePotentialCount = 21;
    repeated uint32 activeSecondaryIds = 22;
    repeated uint32 fateCards = 23;
    TowerRoomBin room = 24;
    repeated uint64 totalDamages = 25;
    uint32 shopRerollTimes = 26;
    uint32 shopRerollPrice = 27;
    bool freeStrengthenAvailable = 28;
}

message TowerCompBin {
    repeated uint32 starTowerLog = 1;
    repeated uint32 starTowerGrowth = 2;
    uint32 towerTickets = 3;
    repeated TowerPotentialPresetBin presets = 4;
    repeated TowerBuildBin builds = 5;
    TowerGameBin currentGame = 6;
    TowerBuildBin lastBuild = 7;
    repeated uint32 fateCards = 8;
    repeated uint32 bookCharIds = 9;
    repeated uint32 bookEventIds = 10;
    repeated uint32 bookBundles = 11;
    repeated uint32 bookPotentialReceivedIds = 12;
    repeated uint32 bookEventReceivedIds = 13;
    repeated uint32 fateCardRewardReceivedIds = 14;
    repeated uint32 npcAffinityRewardReceivedPlotIds = 15;
    repeated uint32 npcAffinityBookNpcIds = 16;
    repeated uint32 npcAffinityBookPlots = 17;
    repeated uint32 npcAffinityBookLevels = 18;
    repeated uint32 npcAffinityBookValues = 19;
    map<uint32, uint32> bookPotentialLevels = 20;
    bool defaultUnlockAllStarTower = 21;
}

message PlayerBasicCompBin {
    // int32 uid = 1;

    // Details
    int64 createTime = 2;         // 创建时间
    string name = 3;
    string signature = 4;
    bool gender = 5;
    int32 headIcon = 6;
    int32 skinId = 7;
    int32 titlePrefix = 8;
    int32 titleSuffix = 9;
    int64 music = 10;
    repeated int32 honor = 11;
    repeated int32 showChars = 12;
    repeated int32 boards = 13;
    int32 level = 14;
    int32 exp = 15;
    int32 energy = 16;
    int64 energyLastUpdate = 17;  // 体力上次恢复时间
    int32 signInIndex = 18;
    int64 lastEpochDay = 19;       // 上次纪元日（用于每日重置）
    int64 lastLogin = 20;          // 上次登录时间
    map<string, uint32> monthlyCardExpireDays = 21;
    map<string, uint32> monthlyCardLastRewardDays = 22;
    repeated string permissions = 23; // 服务器命令使用权限
}

message StoryChoiceBin {
    uint32 group = 1;
    uint32 value = 2;
}

message StoryOptionLogBin {
    repeated StoryChoiceBin major = 1;
    repeated StoryChoiceBin personality = 2;
}

message StoryCompBin {
    repeated uint32 completedStories = 1;
    map<uint32, uint32> completedSets = 2;
    repeated uint32 evidences = 3;
    map<uint32, StoryOptionLogBin> options = 4;
}

message PlayerSaveData {
    // int32 uid = 1;

    PlayerBasicCompBin playerdata = 2;
    CharacterCompBin charComp = 3;
    QuestCompBin questComp = 4;
    AchievementCompBin achievementComp = 5;
    InventoryCompBin inventoryComp = 6;
    MailCompBin mailComp = 7;
    GachaCompBin gachaComp = 8;
    BattlePassCompBin battlePassComp = 9;
    FormationCompBin formationComp = 10;
    TowerCompBin towerComp = 11;
    StoryCompBin storyComp = 12;
}

message GameDiscInfoBin {
    int32 discId = 2;
    int32 level = 3;
    int32 exp = 4;
    int32 phase = 5;
    int32 star = 6;
    
    bool read = 7;
    bool avg = 8;
    
    int64 createTime = 9;
}
