syntax = "proto3";

package ServerOnly;

message PlayerCompBin {
    // int32 uid = 1;

    // Details
    string name = 2;
    string signature = 3;
    bool gender = 4;
    int32 headIcon = 5;
    int32 skinId = 6;
    int32 titlePrefix = 7;
    int32 titleSuffix = 8;
    int64 music = 9;
    repeated int32 honor = 10;
    repeated int32 showChars = 11;
    repeated int32 boards = 12;

    int32 level = 13;
    int32 exp = 14;
    int32 energy = 15;
    int64 energyLastUpdate = 16;  // 体力上次恢复时间

    int32 signInIndex = 17;
    
    int64 lastEpochDay = 18;       // 上次纪元日（用于每日重置）
    int64 lastLogin = 19;          // 上次登录时间
    int64 createTime = 20;         // 创建时间
}
