// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: activity_double_quest_reward_receive.proto
// Protobuf C++ Version: 6.33.4

#ifndef activity_5fdouble_5fquest_5freward_5freceive_2eproto_2epb_2eh
#define activity_5fdouble_5fquest_5freward_5freceive_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "public.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_activity_5fdouble_5fquest_5freward_5freceive_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_activity_5fdouble_5fquest_5freward_5freceive_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_activity_5fdouble_5fquest_5freward_5freceive_2eproto;
}  // extern "C"
namespace proto {
class ActivityDoubleQuestRewardReq;
struct ActivityDoubleQuestRewardReqDefaultTypeInternal;
extern ActivityDoubleQuestRewardReqDefaultTypeInternal _ActivityDoubleQuestRewardReq_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ActivityDoubleQuestRewardReq_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class ActivityDoubleQuestRewardReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.ActivityDoubleQuestRewardReq) */ {
 public:
  inline ActivityDoubleQuestRewardReq() : ActivityDoubleQuestRewardReq(nullptr) {}
  ~ActivityDoubleQuestRewardReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ActivityDoubleQuestRewardReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ActivityDoubleQuestRewardReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ActivityDoubleQuestRewardReq(::google::protobuf::internal::ConstantInitialized);

  inline ActivityDoubleQuestRewardReq(const ActivityDoubleQuestRewardReq& from) : ActivityDoubleQuestRewardReq(nullptr, from) {}
  inline ActivityDoubleQuestRewardReq(ActivityDoubleQuestRewardReq&& from) noexcept
      : ActivityDoubleQuestRewardReq(nullptr, ::std::move(from)) {}
  inline ActivityDoubleQuestRewardReq& operator=(const ActivityDoubleQuestRewardReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActivityDoubleQuestRewardReq& operator=(ActivityDoubleQuestRewardReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActivityDoubleQuestRewardReq& default_instance() {
    return *reinterpret_cast<const ActivityDoubleQuestRewardReq*>(
        &_ActivityDoubleQuestRewardReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ActivityDoubleQuestRewardReq& a, ActivityDoubleQuestRewardReq& b) { a.Swap(&b); }
  inline void Swap(ActivityDoubleQuestRewardReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActivityDoubleQuestRewardReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActivityDoubleQuestRewardReq* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ActivityDoubleQuestRewardReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ActivityDoubleQuestRewardReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ActivityDoubleQuestRewardReq& from) { ActivityDoubleQuestRewardReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ActivityDoubleQuestRewardReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.ActivityDoubleQuestRewardReq"; }

  explicit ActivityDoubleQuestRewardReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ActivityDoubleQuestRewardReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ActivityDoubleQuestRewardReq& from);
  ActivityDoubleQuestRewardReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ActivityDoubleQuestRewardReq&& from) noexcept
      : ActivityDoubleQuestRewardReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextPackageFieldNumber = 2047,
    kActivityIdFieldNumber = 1,
    kQuestIdFieldNumber = 2,
  };
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // uint32 ActivityId = 1;
  void clear_activityid() ;
  ::uint32_t activityid() const;
  void set_activityid(::uint32_t value);

  private:
  ::uint32_t _internal_activityid() const;
  void _internal_set_activityid(::uint32_t value);

  public:
  // uint32 QuestId = 2;
  void clear_questid() ;
  ::uint32_t questid() const;
  void set_questid(::uint32_t value);

  private:
  ::uint32_t _internal_questid() const;
  void _internal_set_questid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.ActivityDoubleQuestRewardReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ActivityDoubleQuestRewardReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    ::uint32_t activityid_;
    ::uint32_t questid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_activity_5fdouble_5fquest_5freward_5freceive_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ActivityDoubleQuestRewardReq_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ActivityDoubleQuestRewardReq

// uint32 ActivityId = 1;
inline void ActivityDoubleQuestRewardReq::clear_activityid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.activityid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t ActivityDoubleQuestRewardReq::activityid() const {
  // @@protoc_insertion_point(field_get:proto.ActivityDoubleQuestRewardReq.ActivityId)
  return _internal_activityid();
}
inline void ActivityDoubleQuestRewardReq::set_activityid(::uint32_t value) {
  _internal_set_activityid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.ActivityDoubleQuestRewardReq.ActivityId)
}
inline ::uint32_t ActivityDoubleQuestRewardReq::_internal_activityid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.activityid_;
}
inline void ActivityDoubleQuestRewardReq::_internal_set_activityid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.activityid_ = value;
}

// uint32 QuestId = 2;
inline void ActivityDoubleQuestRewardReq::clear_questid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.questid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t ActivityDoubleQuestRewardReq::questid() const {
  // @@protoc_insertion_point(field_get:proto.ActivityDoubleQuestRewardReq.QuestId)
  return _internal_questid();
}
inline void ActivityDoubleQuestRewardReq::set_questid(::uint32_t value) {
  _internal_set_questid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.ActivityDoubleQuestRewardReq.QuestId)
}
inline ::uint32_t ActivityDoubleQuestRewardReq::_internal_questid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.questid_;
}
inline void ActivityDoubleQuestRewardReq::_internal_set_questid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.questid_ = value;
}

// bytes NextPackage = 2047;
inline void ActivityDoubleQuestRewardReq::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ActivityDoubleQuestRewardReq::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.ActivityDoubleQuestRewardReq.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ActivityDoubleQuestRewardReq::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.ActivityDoubleQuestRewardReq.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL ActivityDoubleQuestRewardReq::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.ActivityDoubleQuestRewardReq.NextPackage)
  return _s;
}
inline const ::std::string& ActivityDoubleQuestRewardReq::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void ActivityDoubleQuestRewardReq::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ActivityDoubleQuestRewardReq::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ActivityDoubleQuestRewardReq::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.ActivityDoubleQuestRewardReq.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void ActivityDoubleQuestRewardReq::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.ActivityDoubleQuestRewardReq.NextPackage)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // activity_5fdouble_5fquest_5freward_5freceive_2eproto_2epb_2eh
