// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: build_convert_submit.proto
// Protobuf C++ Version: 6.33.4

#include "build_convert_submit.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr BuildConvertSubmitReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        buildids_{},
        _buildids_cached_byte_size_{0},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        activityid_{0u},
        contentid_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR BuildConvertSubmitReq::BuildConvertSubmitReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BuildConvertSubmitReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BuildConvertSubmitReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildConvertSubmitReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildConvertSubmitReqDefaultTypeInternal() {}
  union {
    BuildConvertSubmitReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildConvertSubmitReqDefaultTypeInternal _BuildConvertSubmitReq_default_instance_;

inline constexpr BuildConvertSubmitResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        awarditems_{},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        change_{nullptr},
        number_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR BuildConvertSubmitResp::BuildConvertSubmitResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BuildConvertSubmitResp_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BuildConvertSubmitRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildConvertSubmitRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildConvertSubmitRespDefaultTypeInternal() {}
  union {
    BuildConvertSubmitResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildConvertSubmitRespDefaultTypeInternal _BuildConvertSubmitResp_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_build_5fconvert_5fsubmit_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_build_5fconvert_5fsubmit_2eproto = nullptr;
const ::uint32_t
    TableStruct_build_5fconvert_5fsubmit_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitReq, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitReq, _impl_.activityid_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitReq, _impl_.contentid_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitReq, _impl_.buildids_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitReq, _impl_.nextpackage_),
        2,
        3,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitResp, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitResp, _impl_.change_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitResp, _impl_.awarditems_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitResp, _impl_.number_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertSubmitResp, _impl_.nextpackage_),
        2,
        0,
        3,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::BuildConvertSubmitReq)},
        {11, sizeof(::proto::BuildConvertSubmitResp)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_BuildConvertSubmitReq_default_instance_._instance,
    &::proto::_BuildConvertSubmitResp_default_instance_._instance,
};
const char descriptor_table_protodef_build_5fconvert_5fsubmit_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032build_convert_submit.proto\022\005proto\032\014pub"
    "lic.proto\"f\n\025BuildConvertSubmitReq\022\022\n\nAc"
    "tivityId\030\001 \001(\r\022\021\n\tContentId\030\002 \001(\r\022\020\n\010Bui"
    "ldIds\030\003 \003(\004\022\024\n\013NextPackage\030\377\017 \001(\014\"\205\001\n\026Bu"
    "ildConvertSubmitResp\022!\n\006Change\030\001 \001(\0132\021.p"
    "roto.ChangeInfo\022\"\n\nAwardItems\030\002 \003(\0132\016.pr"
    "oto.ItemTpl\022\016\n\006Number\030\003 \001(\r\022\024\n\013NextPacka"
    "ge\030\377\017 \001(\014b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_build_5fconvert_5fsubmit_2eproto_deps[1] = {
        &::descriptor_table_public_2eproto,
};
static ::absl::once_flag descriptor_table_build_5fconvert_5fsubmit_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_build_5fconvert_5fsubmit_2eproto = {
    false,
    false,
    297,
    descriptor_table_protodef_build_5fconvert_5fsubmit_2eproto,
    "build_convert_submit.proto",
    &descriptor_table_build_5fconvert_5fsubmit_2eproto_once,
    descriptor_table_build_5fconvert_5fsubmit_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_build_5fconvert_5fsubmit_2eproto::offsets,
    file_level_enum_descriptors_build_5fconvert_5fsubmit_2eproto,
    file_level_service_descriptors_build_5fconvert_5fsubmit_2eproto,
};
namespace proto {
// ===================================================================

class BuildConvertSubmitReq::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BuildConvertSubmitReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_._has_bits_);
};

BuildConvertSubmitReq::BuildConvertSubmitReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuildConvertSubmitReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.BuildConvertSubmitReq)
}
PROTOBUF_NDEBUG_INLINE BuildConvertSubmitReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::BuildConvertSubmitReq& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        buildids_{visibility, arena, from.buildids_},
        _buildids_cached_byte_size_{0},
        nextpackage_(arena, from.nextpackage_) {}

BuildConvertSubmitReq::BuildConvertSubmitReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BuildConvertSubmitReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuildConvertSubmitReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BuildConvertSubmitReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, activityid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, activityid_),
           offsetof(Impl_, contentid_) -
               offsetof(Impl_, activityid_) +
               sizeof(Impl_::contentid_));

  // @@protoc_insertion_point(copy_constructor:proto.BuildConvertSubmitReq)
}
PROTOBUF_NDEBUG_INLINE BuildConvertSubmitReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        buildids_{visibility, arena},
        _buildids_cached_byte_size_{0},
        nextpackage_(arena) {}

inline void BuildConvertSubmitReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, activityid_),
           0,
           offsetof(Impl_, contentid_) -
               offsetof(Impl_, activityid_) +
               sizeof(Impl_::contentid_));
}
BuildConvertSubmitReq::~BuildConvertSubmitReq() {
  // @@protoc_insertion_point(destructor:proto.BuildConvertSubmitReq)
  SharedDtor(*this);
}
inline void BuildConvertSubmitReq::SharedDtor(MessageLite& self) {
  BuildConvertSubmitReq& this_ = static_cast<BuildConvertSubmitReq&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BuildConvertSubmitReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BuildConvertSubmitReq(arena);
}
constexpr auto BuildConvertSubmitReq::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.buildids_) +
          decltype(BuildConvertSubmitReq::_impl_.buildids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(BuildConvertSubmitReq), alignof(BuildConvertSubmitReq), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BuildConvertSubmitReq::PlacementNew_,
                                 sizeof(BuildConvertSubmitReq),
                                 alignof(BuildConvertSubmitReq));
  }
}
constexpr auto BuildConvertSubmitReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BuildConvertSubmitReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BuildConvertSubmitReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BuildConvertSubmitReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BuildConvertSubmitReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BuildConvertSubmitReq>(), &BuildConvertSubmitReq::ByteSizeLong,
              &BuildConvertSubmitReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_._cached_size_),
          false,
      },
      &BuildConvertSubmitReq::kDescriptorMethods,
      &descriptor_table_build_5fconvert_5fsubmit_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BuildConvertSubmitReq_class_data_ =
        BuildConvertSubmitReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BuildConvertSubmitReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BuildConvertSubmitReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BuildConvertSubmitReq_class_data_.tc_table);
  return BuildConvertSubmitReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 4, 0, 0, 7>
BuildConvertSubmitReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_._has_bits_),
    0, // no _extensions_
    2047, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    BuildConvertSubmitReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::BuildConvertSubmitReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 ActivityId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BuildConvertSubmitReq, _impl_.activityid_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.activityid_)}},
    // uint32 ContentId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BuildConvertSubmitReq, _impl_.contentid_), 3>(),
     {16, 3, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.contentid_)}},
    // repeated uint64 BuildIds = 3;
    {::_pbi::TcParser::FastV64P1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.buildids_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes NextPackage = 2047;
    {::_pbi::TcParser::FastBS2,
     {32762, 1, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.nextpackage_)}},
  }}, {{
    2047, 0, 1,
    65534, 3,
    65535, 65535
  }}, {{
    // uint32 ActivityId = 1;
    {PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.activityid_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 ContentId = 2;
    {PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.contentid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated uint64 BuildIds = 3;
    {PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.buildids_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.nextpackage_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void BuildConvertSubmitReq::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.BuildConvertSubmitReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.buildids_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.nextpackage_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.activityid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.contentid_) -
        reinterpret_cast<char*>(&_impl_.activityid_)) + sizeof(_impl_.contentid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BuildConvertSubmitReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BuildConvertSubmitReq& this_ = static_cast<const BuildConvertSubmitReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BuildConvertSubmitReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BuildConvertSubmitReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.BuildConvertSubmitReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 ActivityId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_activityid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_activityid(), target);
    }
  }

  // uint32 ContentId = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_contentid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_contentid(), target);
    }
  }

  // repeated uint64 BuildIds = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._buildids_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt64Packed(
            3, this_._internal_buildids(), byte_size, target);
      }
    }
  }

  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.BuildConvertSubmitReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BuildConvertSubmitReq::ByteSizeLong(const MessageLite& base) {
  const BuildConvertSubmitReq& this_ = static_cast<const BuildConvertSubmitReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BuildConvertSubmitReq::ByteSizeLong() const {
  const BuildConvertSubmitReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.BuildConvertSubmitReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // repeated uint64 BuildIds = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt64SizeWithPackedTagSize(
              this_._internal_buildids(), 1,
              this_._impl_._buildids_cached_byte_size_);
    }
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
    // uint32 ActivityId = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_activityid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_activityid());
      }
    }
    // uint32 ContentId = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_contentid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_contentid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BuildConvertSubmitReq::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BuildConvertSubmitReq*>(&to_msg);
  auto& from = static_cast<const BuildConvertSubmitReq&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.BuildConvertSubmitReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_buildids()->MergeFrom(from._internal_buildids());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_activityid() != 0) {
        _this->_impl_.activityid_ = from._impl_.activityid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_contentid() != 0) {
        _this->_impl_.contentid_ = from._impl_.contentid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BuildConvertSubmitReq::CopyFrom(const BuildConvertSubmitReq& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.BuildConvertSubmitReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BuildConvertSubmitReq::InternalSwap(BuildConvertSubmitReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.buildids_.InternalSwap(&other->_impl_.buildids_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.contentid_)
      + sizeof(BuildConvertSubmitReq::_impl_.contentid_)
      - PROTOBUF_FIELD_OFFSET(BuildConvertSubmitReq, _impl_.activityid_)>(
          reinterpret_cast<char*>(&_impl_.activityid_),
          reinterpret_cast<char*>(&other->_impl_.activityid_));
}

::google::protobuf::Metadata BuildConvertSubmitReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BuildConvertSubmitResp::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BuildConvertSubmitResp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_._has_bits_);
};

void BuildConvertSubmitResp::clear_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.change_ != nullptr) _impl_.change_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
void BuildConvertSubmitResp::clear_awarditems() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.awarditems_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
BuildConvertSubmitResp::BuildConvertSubmitResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuildConvertSubmitResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.BuildConvertSubmitResp)
}
PROTOBUF_NDEBUG_INLINE BuildConvertSubmitResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::BuildConvertSubmitResp& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        awarditems_{visibility, arena, from.awarditems_},
        nextpackage_(arena, from.nextpackage_) {}

BuildConvertSubmitResp::BuildConvertSubmitResp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BuildConvertSubmitResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuildConvertSubmitResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BuildConvertSubmitResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.change_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_)
                : nullptr;
  _impl_.number_ = from._impl_.number_;

  // @@protoc_insertion_point(copy_constructor:proto.BuildConvertSubmitResp)
}
PROTOBUF_NDEBUG_INLINE BuildConvertSubmitResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        awarditems_{visibility, arena},
        nextpackage_(arena) {}

inline void BuildConvertSubmitResp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, change_),
           0,
           offsetof(Impl_, number_) -
               offsetof(Impl_, change_) +
               sizeof(Impl_::number_));
}
BuildConvertSubmitResp::~BuildConvertSubmitResp() {
  // @@protoc_insertion_point(destructor:proto.BuildConvertSubmitResp)
  SharedDtor(*this);
}
inline void BuildConvertSubmitResp::SharedDtor(MessageLite& self) {
  BuildConvertSubmitResp& this_ = static_cast<BuildConvertSubmitResp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  delete this_._impl_.change_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BuildConvertSubmitResp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BuildConvertSubmitResp(arena);
}
constexpr auto BuildConvertSubmitResp::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.awarditems_) +
          decltype(BuildConvertSubmitResp::_impl_.awarditems_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(BuildConvertSubmitResp), alignof(BuildConvertSubmitResp), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BuildConvertSubmitResp::PlacementNew_,
                                 sizeof(BuildConvertSubmitResp),
                                 alignof(BuildConvertSubmitResp));
  }
}
constexpr auto BuildConvertSubmitResp::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BuildConvertSubmitResp_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BuildConvertSubmitResp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BuildConvertSubmitResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BuildConvertSubmitResp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BuildConvertSubmitResp>(), &BuildConvertSubmitResp::ByteSizeLong,
              &BuildConvertSubmitResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_._cached_size_),
          false,
      },
      &BuildConvertSubmitResp::kDescriptorMethods,
      &descriptor_table_build_5fconvert_5fsubmit_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BuildConvertSubmitResp_class_data_ =
        BuildConvertSubmitResp::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BuildConvertSubmitResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BuildConvertSubmitResp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BuildConvertSubmitResp_class_data_.tc_table);
  return BuildConvertSubmitResp_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 4, 2, 0, 7>
BuildConvertSubmitResp::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_._has_bits_),
    0, // no _extensions_
    2047, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BuildConvertSubmitResp_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::BuildConvertSubmitResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .proto.ChangeInfo Change = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 2, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.change_)}},
    // repeated .proto.ItemTpl AwardItems = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 1,
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.awarditems_)}},
    // uint32 Number = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BuildConvertSubmitResp, _impl_.number_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.number_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes NextPackage = 2047;
    {::_pbi::TcParser::FastBS2,
     {32762, 1, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.nextpackage_)}},
  }}, {{
    2047, 0, 1,
    65534, 3,
    65535, 65535
  }}, {{
    // .proto.ChangeInfo Change = 1;
    {PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.change_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .proto.ItemTpl AwardItems = 2;
    {PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.awarditems_), _Internal::kHasBitsOffset + 0, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 Number = 3;
    {PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.number_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.nextpackage_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::ChangeInfo>()},
      {::_pbi::TcParser::GetTable<::proto::ItemTpl>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BuildConvertSubmitResp::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.BuildConvertSubmitResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.awarditems_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.nextpackage_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.change_ != nullptr);
      _impl_.change_->Clear();
    }
  }
  _impl_.number_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BuildConvertSubmitResp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BuildConvertSubmitResp& this_ = static_cast<const BuildConvertSubmitResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BuildConvertSubmitResp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BuildConvertSubmitResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.BuildConvertSubmitResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .proto.ChangeInfo Change = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.change_, this_._impl_.change_->GetCachedSize(), target,
        stream);
  }

  // repeated .proto.ItemTpl AwardItems = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_awarditems_size());
         i < n; i++) {
      const auto& repfield = this_._internal_awarditems().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // uint32 Number = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_number() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_number(), target);
    }
  }

  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.BuildConvertSubmitResp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BuildConvertSubmitResp::ByteSizeLong(const MessageLite& base) {
  const BuildConvertSubmitResp& this_ = static_cast<const BuildConvertSubmitResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BuildConvertSubmitResp::ByteSizeLong() const {
  const BuildConvertSubmitResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.BuildConvertSubmitResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // repeated .proto.ItemTpl AwardItems = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_awarditems_size();
      for (const auto& msg : this_._internal_awarditems()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
    // .proto.ChangeInfo Change = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.change_);
    }
    // uint32 Number = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_number() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_number());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BuildConvertSubmitResp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BuildConvertSubmitResp*>(&to_msg);
  auto& from = static_cast<const BuildConvertSubmitResp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.BuildConvertSubmitResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_awarditems()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_awarditems());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.change_ != nullptr);
      if (_this->_impl_.change_ == nullptr) {
        _this->_impl_.change_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_);
      } else {
        _this->_impl_.change_->MergeFrom(*from._impl_.change_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_number() != 0) {
        _this->_impl_.number_ = from._impl_.number_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BuildConvertSubmitResp::CopyFrom(const BuildConvertSubmitResp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.BuildConvertSubmitResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BuildConvertSubmitResp::InternalSwap(BuildConvertSubmitResp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.awarditems_.InternalSwap(&other->_impl_.awarditems_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.number_)
      + sizeof(BuildConvertSubmitResp::_impl_.number_)
      - PROTOBUF_FIELD_OFFSET(BuildConvertSubmitResp, _impl_.change_)>(
          reinterpret_cast<char*>(&_impl_.change_),
          reinterpret_cast<char*>(&other->_impl_.change_));
}

::google::protobuf::Metadata BuildConvertSubmitResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_build_5fconvert_5fsubmit_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
