// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: build_convert_detail_list_get.proto
// Protobuf C++ Version: 6.33.4

#include "build_convert_detail_list_get.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr BuildConvertDetailListGetResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        details_{},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR BuildConvertDetailListGetResp::BuildConvertDetailListGetResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BuildConvertDetailListGetResp_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BuildConvertDetailListGetRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildConvertDetailListGetRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildConvertDetailListGetRespDefaultTypeInternal() {}
  union {
    BuildConvertDetailListGetResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildConvertDetailListGetRespDefaultTypeInternal _BuildConvertDetailListGetResp_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_build_5fconvert_5fdetail_5flist_5fget_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_build_5fconvert_5fdetail_5flist_5fget_2eproto = nullptr;
const ::uint32_t
    TableStruct_build_5fconvert_5fdetail_5flist_5fget_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertDetailListGetResp, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertDetailListGetResp, _impl_.details_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertDetailListGetResp, _impl_.nextpackage_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::BuildConvertDetailListGetResp)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_BuildConvertDetailListGetResp_default_instance_._instance,
};
const char descriptor_table_protodef_build_5fconvert_5fdetail_5flist_5fget_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n#build_convert_detail_list_get.proto\022\005p"
    "roto\032\027public_star_tower.proto\"a\n\035BuildCo"
    "nvertDetailListGetResp\022*\n\007Details\030\001 \003(\0132"
    "\031.proto.StarTowerBuildInfo\022\024\n\013NextPackag"
    "e\030\377\017 \001(\014b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_build_5fconvert_5fdetail_5flist_5fget_2eproto_deps[1] = {
        &::descriptor_table_public_5fstar_5ftower_2eproto,
};
static ::absl::once_flag descriptor_table_build_5fconvert_5fdetail_5flist_5fget_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_build_5fconvert_5fdetail_5flist_5fget_2eproto = {
    false,
    false,
    176,
    descriptor_table_protodef_build_5fconvert_5fdetail_5flist_5fget_2eproto,
    "build_convert_detail_list_get.proto",
    &descriptor_table_build_5fconvert_5fdetail_5flist_5fget_2eproto_once,
    descriptor_table_build_5fconvert_5fdetail_5flist_5fget_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_build_5fconvert_5fdetail_5flist_5fget_2eproto::offsets,
    file_level_enum_descriptors_build_5fconvert_5fdetail_5flist_5fget_2eproto,
    file_level_service_descriptors_build_5fconvert_5fdetail_5flist_5fget_2eproto,
};
namespace proto {
// ===================================================================

class BuildConvertDetailListGetResp::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BuildConvertDetailListGetResp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BuildConvertDetailListGetResp, _impl_._has_bits_);
};

void BuildConvertDetailListGetResp::clear_details() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.details_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
BuildConvertDetailListGetResp::BuildConvertDetailListGetResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuildConvertDetailListGetResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.BuildConvertDetailListGetResp)
}
PROTOBUF_NDEBUG_INLINE BuildConvertDetailListGetResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::BuildConvertDetailListGetResp& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        details_{visibility, arena, from.details_},
        nextpackage_(arena, from.nextpackage_) {}

BuildConvertDetailListGetResp::BuildConvertDetailListGetResp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BuildConvertDetailListGetResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuildConvertDetailListGetResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BuildConvertDetailListGetResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.BuildConvertDetailListGetResp)
}
PROTOBUF_NDEBUG_INLINE BuildConvertDetailListGetResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        details_{visibility, arena},
        nextpackage_(arena) {}

inline void BuildConvertDetailListGetResp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BuildConvertDetailListGetResp::~BuildConvertDetailListGetResp() {
  // @@protoc_insertion_point(destructor:proto.BuildConvertDetailListGetResp)
  SharedDtor(*this);
}
inline void BuildConvertDetailListGetResp::SharedDtor(MessageLite& self) {
  BuildConvertDetailListGetResp& this_ = static_cast<BuildConvertDetailListGetResp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BuildConvertDetailListGetResp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BuildConvertDetailListGetResp(arena);
}
constexpr auto BuildConvertDetailListGetResp::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BuildConvertDetailListGetResp, _impl_.details_) +
          decltype(BuildConvertDetailListGetResp::_impl_.details_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(BuildConvertDetailListGetResp), alignof(BuildConvertDetailListGetResp), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BuildConvertDetailListGetResp::PlacementNew_,
                                 sizeof(BuildConvertDetailListGetResp),
                                 alignof(BuildConvertDetailListGetResp));
  }
}
constexpr auto BuildConvertDetailListGetResp::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BuildConvertDetailListGetResp_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BuildConvertDetailListGetResp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BuildConvertDetailListGetResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BuildConvertDetailListGetResp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BuildConvertDetailListGetResp>(), &BuildConvertDetailListGetResp::ByteSizeLong,
              &BuildConvertDetailListGetResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BuildConvertDetailListGetResp, _impl_._cached_size_),
          false,
      },
      &BuildConvertDetailListGetResp::kDescriptorMethods,
      &descriptor_table_build_5fconvert_5fdetail_5flist_5fget_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BuildConvertDetailListGetResp_class_data_ =
        BuildConvertDetailListGetResp::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BuildConvertDetailListGetResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BuildConvertDetailListGetResp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BuildConvertDetailListGetResp_class_data_.tc_table);
  return BuildConvertDetailListGetResp_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 2, 1, 0, 7>
BuildConvertDetailListGetResp::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BuildConvertDetailListGetResp, _impl_._has_bits_),
    0, // no _extensions_
    2047, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BuildConvertDetailListGetResp_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::BuildConvertDetailListGetResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .proto.StarTowerBuildInfo Details = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertDetailListGetResp, _impl_.details_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes NextPackage = 2047;
    {::_pbi::TcParser::FastBS2,
     {32762, 1, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertDetailListGetResp, _impl_.nextpackage_)}},
  }}, {{
    2047, 0, 1,
    65534, 1,
    65535, 65535
  }}, {{
    // repeated .proto.StarTowerBuildInfo Details = 1;
    {PROTOBUF_FIELD_OFFSET(BuildConvertDetailListGetResp, _impl_.details_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(BuildConvertDetailListGetResp, _impl_.nextpackage_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::StarTowerBuildInfo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BuildConvertDetailListGetResp::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.BuildConvertDetailListGetResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.details_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.nextpackage_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BuildConvertDetailListGetResp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BuildConvertDetailListGetResp& this_ = static_cast<const BuildConvertDetailListGetResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BuildConvertDetailListGetResp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BuildConvertDetailListGetResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.BuildConvertDetailListGetResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .proto.StarTowerBuildInfo Details = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_details_size());
         i < n; i++) {
      const auto& repfield = this_._internal_details().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.BuildConvertDetailListGetResp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BuildConvertDetailListGetResp::ByteSizeLong(const MessageLite& base) {
  const BuildConvertDetailListGetResp& this_ = static_cast<const BuildConvertDetailListGetResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BuildConvertDetailListGetResp::ByteSizeLong() const {
  const BuildConvertDetailListGetResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.BuildConvertDetailListGetResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .proto.StarTowerBuildInfo Details = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_details_size();
      for (const auto& msg : this_._internal_details()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BuildConvertDetailListGetResp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BuildConvertDetailListGetResp*>(&to_msg);
  auto& from = static_cast<const BuildConvertDetailListGetResp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.BuildConvertDetailListGetResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_details()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_details());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BuildConvertDetailListGetResp::CopyFrom(const BuildConvertDetailListGetResp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.BuildConvertDetailListGetResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BuildConvertDetailListGetResp::InternalSwap(BuildConvertDetailListGetResp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.details_.InternalSwap(&other->_impl_.details_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
}

::google::protobuf::Metadata BuildConvertDetailListGetResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_build_5fconvert_5fdetail_5flist_5fget_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
