// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: build_convert_group_reward_receive.proto
// Protobuf C++ Version: 6.33.4

#include "build_convert_group_reward_receive.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr BuildConvertGroupRewardReceiveResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ids_{},
        _ids_cached_byte_size_{0},
        awarditems_{},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        change_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR BuildConvertGroupRewardReceiveResp::BuildConvertGroupRewardReceiveResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BuildConvertGroupRewardReceiveResp_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BuildConvertGroupRewardReceiveRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BuildConvertGroupRewardReceiveRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BuildConvertGroupRewardReceiveRespDefaultTypeInternal() {}
  union {
    BuildConvertGroupRewardReceiveResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BuildConvertGroupRewardReceiveRespDefaultTypeInternal _BuildConvertGroupRewardReceiveResp_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_build_5fconvert_5fgroup_5freward_5freceive_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_build_5fconvert_5fgroup_5freward_5freceive_2eproto = nullptr;
const ::uint32_t
    TableStruct_build_5fconvert_5fgroup_5freward_5freceive_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertGroupRewardReceiveResp, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertGroupRewardReceiveResp, _impl_.ids_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertGroupRewardReceiveResp, _impl_.change_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertGroupRewardReceiveResp, _impl_.awarditems_),
        PROTOBUF_FIELD_OFFSET(::proto::BuildConvertGroupRewardReceiveResp, _impl_.nextpackage_),
        0,
        3,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::BuildConvertGroupRewardReceiveResp)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_BuildConvertGroupRewardReceiveResp_default_instance_._instance,
};
const char descriptor_table_protodef_build_5fconvert_5fgroup_5freward_5freceive_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n(build_convert_group_reward_receive.pro"
    "to\022\005proto\032\014public.proto\"\216\001\n\"BuildConvert"
    "GroupRewardReceiveResp\022\013\n\003Ids\030\001 \003(\r\022!\n\006C"
    "hange\030\002 \001(\0132\021.proto.ChangeInfo\022\"\n\nAwardI"
    "tems\030\003 \003(\0132\016.proto.ItemTpl\022\024\n\013NextPackag"
    "e\030\377\017 \001(\014b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_build_5fconvert_5fgroup_5freward_5freceive_2eproto_deps[1] = {
        &::descriptor_table_public_2eproto,
};
static ::absl::once_flag descriptor_table_build_5fconvert_5fgroup_5freward_5freceive_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_build_5fconvert_5fgroup_5freward_5freceive_2eproto = {
    false,
    false,
    216,
    descriptor_table_protodef_build_5fconvert_5fgroup_5freward_5freceive_2eproto,
    "build_convert_group_reward_receive.proto",
    &descriptor_table_build_5fconvert_5fgroup_5freward_5freceive_2eproto_once,
    descriptor_table_build_5fconvert_5fgroup_5freward_5freceive_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_build_5fconvert_5fgroup_5freward_5freceive_2eproto::offsets,
    file_level_enum_descriptors_build_5fconvert_5fgroup_5freward_5freceive_2eproto,
    file_level_service_descriptors_build_5fconvert_5fgroup_5freward_5freceive_2eproto,
};
namespace proto {
// ===================================================================

class BuildConvertGroupRewardReceiveResp::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BuildConvertGroupRewardReceiveResp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_._has_bits_);
};

void BuildConvertGroupRewardReceiveResp::clear_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.change_ != nullptr) _impl_.change_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
void BuildConvertGroupRewardReceiveResp::clear_awarditems() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.awarditems_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
BuildConvertGroupRewardReceiveResp::BuildConvertGroupRewardReceiveResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuildConvertGroupRewardReceiveResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.BuildConvertGroupRewardReceiveResp)
}
PROTOBUF_NDEBUG_INLINE BuildConvertGroupRewardReceiveResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::BuildConvertGroupRewardReceiveResp& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ids_{visibility, arena, from.ids_},
        _ids_cached_byte_size_{0},
        awarditems_{visibility, arena, from.awarditems_},
        nextpackage_(arena, from.nextpackage_) {}

BuildConvertGroupRewardReceiveResp::BuildConvertGroupRewardReceiveResp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BuildConvertGroupRewardReceiveResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BuildConvertGroupRewardReceiveResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BuildConvertGroupRewardReceiveResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.change_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:proto.BuildConvertGroupRewardReceiveResp)
}
PROTOBUF_NDEBUG_INLINE BuildConvertGroupRewardReceiveResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ids_{visibility, arena},
        _ids_cached_byte_size_{0},
        awarditems_{visibility, arena},
        nextpackage_(arena) {}

inline void BuildConvertGroupRewardReceiveResp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.change_ = {};
}
BuildConvertGroupRewardReceiveResp::~BuildConvertGroupRewardReceiveResp() {
  // @@protoc_insertion_point(destructor:proto.BuildConvertGroupRewardReceiveResp)
  SharedDtor(*this);
}
inline void BuildConvertGroupRewardReceiveResp::SharedDtor(MessageLite& self) {
  BuildConvertGroupRewardReceiveResp& this_ = static_cast<BuildConvertGroupRewardReceiveResp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  delete this_._impl_.change_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BuildConvertGroupRewardReceiveResp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BuildConvertGroupRewardReceiveResp(arena);
}
constexpr auto BuildConvertGroupRewardReceiveResp::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.ids_) +
          decltype(BuildConvertGroupRewardReceiveResp::_impl_.ids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.awarditems_) +
          decltype(BuildConvertGroupRewardReceiveResp::_impl_.awarditems_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(BuildConvertGroupRewardReceiveResp), alignof(BuildConvertGroupRewardReceiveResp), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BuildConvertGroupRewardReceiveResp::PlacementNew_,
                                 sizeof(BuildConvertGroupRewardReceiveResp),
                                 alignof(BuildConvertGroupRewardReceiveResp));
  }
}
constexpr auto BuildConvertGroupRewardReceiveResp::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BuildConvertGroupRewardReceiveResp_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BuildConvertGroupRewardReceiveResp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BuildConvertGroupRewardReceiveResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BuildConvertGroupRewardReceiveResp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BuildConvertGroupRewardReceiveResp>(), &BuildConvertGroupRewardReceiveResp::ByteSizeLong,
              &BuildConvertGroupRewardReceiveResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_._cached_size_),
          false,
      },
      &BuildConvertGroupRewardReceiveResp::kDescriptorMethods,
      &descriptor_table_build_5fconvert_5fgroup_5freward_5freceive_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BuildConvertGroupRewardReceiveResp_class_data_ =
        BuildConvertGroupRewardReceiveResp::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BuildConvertGroupRewardReceiveResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BuildConvertGroupRewardReceiveResp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BuildConvertGroupRewardReceiveResp_class_data_.tc_table);
  return BuildConvertGroupRewardReceiveResp_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 4, 2, 0, 7>
BuildConvertGroupRewardReceiveResp::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_._has_bits_),
    0, // no _extensions_
    2047, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    BuildConvertGroupRewardReceiveResp_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::BuildConvertGroupRewardReceiveResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated uint32 Ids = 1;
    {::_pbi::TcParser::FastV32P1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.ids_)}},
    // .proto.ChangeInfo Change = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 3, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.change_)}},
    // repeated .proto.ItemTpl AwardItems = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 1, 1,
      PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.awarditems_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes NextPackage = 2047;
    {::_pbi::TcParser::FastBS2,
     {32762, 2, 0,
      PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.nextpackage_)}},
  }}, {{
    2047, 0, 1,
    65534, 3,
    65535, 65535
  }}, {{
    // repeated uint32 Ids = 1;
    {PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.ids_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // .proto.ChangeInfo Change = 2;
    {PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.change_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .proto.ItemTpl AwardItems = 3;
    {PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.awarditems_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(BuildConvertGroupRewardReceiveResp, _impl_.nextpackage_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::ChangeInfo>()},
      {::_pbi::TcParser::GetTable<::proto::ItemTpl>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void BuildConvertGroupRewardReceiveResp::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.BuildConvertGroupRewardReceiveResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.ids_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.awarditems_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.nextpackage_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.change_ != nullptr);
      _impl_.change_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BuildConvertGroupRewardReceiveResp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BuildConvertGroupRewardReceiveResp& this_ = static_cast<const BuildConvertGroupRewardReceiveResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BuildConvertGroupRewardReceiveResp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BuildConvertGroupRewardReceiveResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.BuildConvertGroupRewardReceiveResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated uint32 Ids = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._ids_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            1, this_._internal_ids(), byte_size, target);
      }
    }
  }

  // .proto.ChangeInfo Change = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.change_, this_._impl_.change_->GetCachedSize(), target,
        stream);
  }

  // repeated .proto.ItemTpl AwardItems = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_awarditems_size());
         i < n; i++) {
      const auto& repfield = this_._internal_awarditems().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              3, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.BuildConvertGroupRewardReceiveResp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BuildConvertGroupRewardReceiveResp::ByteSizeLong(const MessageLite& base) {
  const BuildConvertGroupRewardReceiveResp& this_ = static_cast<const BuildConvertGroupRewardReceiveResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BuildConvertGroupRewardReceiveResp::ByteSizeLong() const {
  const BuildConvertGroupRewardReceiveResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.BuildConvertGroupRewardReceiveResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // repeated uint32 Ids = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_ids(), 1,
              this_._impl_._ids_cached_byte_size_);
    }
    // repeated .proto.ItemTpl AwardItems = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_awarditems_size();
      for (const auto& msg : this_._internal_awarditems()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
    // .proto.ChangeInfo Change = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.change_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BuildConvertGroupRewardReceiveResp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<BuildConvertGroupRewardReceiveResp*>(&to_msg);
  auto& from = static_cast<const BuildConvertGroupRewardReceiveResp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.BuildConvertGroupRewardReceiveResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_ids()->MergeFrom(from._internal_ids());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_awarditems()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_awarditems());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.change_ != nullptr);
      if (_this->_impl_.change_ == nullptr) {
        _this->_impl_.change_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_);
      } else {
        _this->_impl_.change_->MergeFrom(*from._impl_.change_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void BuildConvertGroupRewardReceiveResp::CopyFrom(const BuildConvertGroupRewardReceiveResp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.BuildConvertGroupRewardReceiveResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BuildConvertGroupRewardReceiveResp::InternalSwap(BuildConvertGroupRewardReceiveResp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.ids_.InternalSwap(&other->_impl_.ids_);
  _impl_.awarditems_.InternalSwap(&other->_impl_.awarditems_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
  swap(_impl_.change_, other->_impl_.change_);
}

::google::protobuf::Metadata BuildConvertGroupRewardReceiveResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_build_5fconvert_5fgroup_5freward_5freceive_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
