// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: char_gem_generate.proto
// Protobuf C++ Version: 6.33.4

#ifndef char_5fgem_5fgenerate_2eproto_2epb_2eh
#define char_5fgem_5fgenerate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "public.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_char_5fgem_5fgenerate_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_char_5fgem_5fgenerate_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_char_5fgem_5fgenerate_2eproto;
}  // extern "C"
namespace proto {
class CharGemGenerateReq;
struct CharGemGenerateReqDefaultTypeInternal;
extern CharGemGenerateReqDefaultTypeInternal _CharGemGenerateReq_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CharGemGenerateReq_class_data_;
class CharGemGenerateResp;
struct CharGemGenerateRespDefaultTypeInternal;
extern CharGemGenerateRespDefaultTypeInternal _CharGemGenerateResp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CharGemGenerateResp_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class CharGemGenerateReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CharGemGenerateReq) */ {
 public:
  inline CharGemGenerateReq() : CharGemGenerateReq(nullptr) {}
  ~CharGemGenerateReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CharGemGenerateReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CharGemGenerateReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CharGemGenerateReq(::google::protobuf::internal::ConstantInitialized);

  inline CharGemGenerateReq(const CharGemGenerateReq& from) : CharGemGenerateReq(nullptr, from) {}
  inline CharGemGenerateReq(CharGemGenerateReq&& from) noexcept
      : CharGemGenerateReq(nullptr, ::std::move(from)) {}
  inline CharGemGenerateReq& operator=(const CharGemGenerateReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CharGemGenerateReq& operator=(CharGemGenerateReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CharGemGenerateReq& default_instance() {
    return *reinterpret_cast<const CharGemGenerateReq*>(
        &_CharGemGenerateReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CharGemGenerateReq& a, CharGemGenerateReq& b) { a.Swap(&b); }
  inline void Swap(CharGemGenerateReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CharGemGenerateReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CharGemGenerateReq* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CharGemGenerateReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CharGemGenerateReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CharGemGenerateReq& from) { CharGemGenerateReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CharGemGenerateReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CharGemGenerateReq"; }

  explicit CharGemGenerateReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CharGemGenerateReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CharGemGenerateReq& from);
  CharGemGenerateReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CharGemGenerateReq&& from) noexcept
      : CharGemGenerateReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextPackageFieldNumber = 2047,
    kCharIdFieldNumber = 1,
    kSlotIdFieldNumber = 2,
  };
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // uint32 CharId = 1;
  void clear_charid() ;
  ::uint32_t charid() const;
  void set_charid(::uint32_t value);

  private:
  ::uint32_t _internal_charid() const;
  void _internal_set_charid(::uint32_t value);

  public:
  // uint32 SlotId = 2;
  void clear_slotid() ;
  ::uint32_t slotid() const;
  void set_slotid(::uint32_t value);

  private:
  ::uint32_t _internal_slotid() const;
  void _internal_set_slotid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.CharGemGenerateReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CharGemGenerateReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    ::uint32_t charid_;
    ::uint32_t slotid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_char_5fgem_5fgenerate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CharGemGenerateReq_class_data_;
// -------------------------------------------------------------------

class CharGemGenerateResp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CharGemGenerateResp) */ {
 public:
  inline CharGemGenerateResp() : CharGemGenerateResp(nullptr) {}
  ~CharGemGenerateResp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CharGemGenerateResp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CharGemGenerateResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CharGemGenerateResp(::google::protobuf::internal::ConstantInitialized);

  inline CharGemGenerateResp(const CharGemGenerateResp& from) : CharGemGenerateResp(nullptr, from) {}
  inline CharGemGenerateResp(CharGemGenerateResp&& from) noexcept
      : CharGemGenerateResp(nullptr, ::std::move(from)) {}
  inline CharGemGenerateResp& operator=(const CharGemGenerateResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline CharGemGenerateResp& operator=(CharGemGenerateResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CharGemGenerateResp& default_instance() {
    return *reinterpret_cast<const CharGemGenerateResp*>(
        &_CharGemGenerateResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CharGemGenerateResp& a, CharGemGenerateResp& b) { a.Swap(&b); }
  inline void Swap(CharGemGenerateResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CharGemGenerateResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CharGemGenerateResp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CharGemGenerateResp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CharGemGenerateResp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CharGemGenerateResp& from) { CharGemGenerateResp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CharGemGenerateResp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CharGemGenerateResp"; }

  explicit CharGemGenerateResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CharGemGenerateResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CharGemGenerateResp& from);
  CharGemGenerateResp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CharGemGenerateResp&& from) noexcept
      : CharGemGenerateResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextPackageFieldNumber = 2047,
    kCharGemFieldNumber = 1,
    kChangeInfoFieldNumber = 2,
  };
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // .proto.CharGem CharGem = 1;
  bool has_chargem() const;
  void clear_chargem() ;
  const ::proto::CharGem& chargem() const;
  [[nodiscard]] ::proto::CharGem* PROTOBUF_NULLABLE release_chargem();
  ::proto::CharGem* PROTOBUF_NONNULL mutable_chargem();
  void set_allocated_chargem(::proto::CharGem* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_chargem(::proto::CharGem* PROTOBUF_NULLABLE value);
  ::proto::CharGem* PROTOBUF_NULLABLE unsafe_arena_release_chargem();

  private:
  const ::proto::CharGem& _internal_chargem() const;
  ::proto::CharGem* PROTOBUF_NONNULL _internal_mutable_chargem();

  public:
  // .proto.ChangeInfo ChangeInfo = 2;
  bool has_changeinfo() const;
  void clear_changeinfo() ;
  const ::proto::ChangeInfo& changeinfo() const;
  [[nodiscard]] ::proto::ChangeInfo* PROTOBUF_NULLABLE release_changeinfo();
  ::proto::ChangeInfo* PROTOBUF_NONNULL mutable_changeinfo();
  void set_allocated_changeinfo(::proto::ChangeInfo* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_changeinfo(::proto::ChangeInfo* PROTOBUF_NULLABLE value);
  ::proto::ChangeInfo* PROTOBUF_NULLABLE unsafe_arena_release_changeinfo();

  private:
  const ::proto::ChangeInfo& _internal_changeinfo() const;
  ::proto::ChangeInfo* PROTOBUF_NONNULL _internal_mutable_changeinfo();

  public:
  // @@protoc_insertion_point(class_scope:proto.CharGemGenerateResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   2, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CharGemGenerateResp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    ::proto::CharGem* PROTOBUF_NULLABLE chargem_;
    ::proto::ChangeInfo* PROTOBUF_NULLABLE changeinfo_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_char_5fgem_5fgenerate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CharGemGenerateResp_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CharGemGenerateReq

// uint32 CharId = 1;
inline void CharGemGenerateReq::clear_charid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.charid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t CharGemGenerateReq::charid() const {
  // @@protoc_insertion_point(field_get:proto.CharGemGenerateReq.CharId)
  return _internal_charid();
}
inline void CharGemGenerateReq::set_charid(::uint32_t value) {
  _internal_set_charid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.CharGemGenerateReq.CharId)
}
inline ::uint32_t CharGemGenerateReq::_internal_charid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.charid_;
}
inline void CharGemGenerateReq::_internal_set_charid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.charid_ = value;
}

// uint32 SlotId = 2;
inline void CharGemGenerateReq::clear_slotid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slotid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t CharGemGenerateReq::slotid() const {
  // @@protoc_insertion_point(field_get:proto.CharGemGenerateReq.SlotId)
  return _internal_slotid();
}
inline void CharGemGenerateReq::set_slotid(::uint32_t value) {
  _internal_set_slotid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.CharGemGenerateReq.SlotId)
}
inline ::uint32_t CharGemGenerateReq::_internal_slotid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.slotid_;
}
inline void CharGemGenerateReq::_internal_set_slotid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slotid_ = value;
}

// bytes NextPackage = 2047;
inline void CharGemGenerateReq::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CharGemGenerateReq::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemGenerateReq.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CharGemGenerateReq::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CharGemGenerateReq.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL CharGemGenerateReq::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.CharGemGenerateReq.NextPackage)
  return _s;
}
inline const ::std::string& CharGemGenerateReq::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void CharGemGenerateReq::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CharGemGenerateReq::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CharGemGenerateReq::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemGenerateReq.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void CharGemGenerateReq::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemGenerateReq.NextPackage)
}

// -------------------------------------------------------------------

// CharGemGenerateResp

// .proto.CharGem CharGem = 1;
inline bool CharGemGenerateResp::has_chargem() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.chargem_ != nullptr);
  return value;
}
inline const ::proto::CharGem& CharGemGenerateResp::_internal_chargem() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::CharGem* p = _impl_.chargem_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::CharGem&>(::proto::_CharGem_default_instance_);
}
inline const ::proto::CharGem& CharGemGenerateResp::chargem() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemGenerateResp.CharGem)
  return _internal_chargem();
}
inline void CharGemGenerateResp::unsafe_arena_set_allocated_chargem(
    ::proto::CharGem* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.chargem_);
  }
  _impl_.chargem_ = reinterpret_cast<::proto::CharGem*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.CharGemGenerateResp.CharGem)
}
inline ::proto::CharGem* PROTOBUF_NULLABLE CharGemGenerateResp::release_chargem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::CharGem* released = _impl_.chargem_;
  _impl_.chargem_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::CharGem* PROTOBUF_NULLABLE CharGemGenerateResp::unsafe_arena_release_chargem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemGenerateResp.CharGem)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::CharGem* temp = _impl_.chargem_;
  _impl_.chargem_ = nullptr;
  return temp;
}
inline ::proto::CharGem* PROTOBUF_NONNULL CharGemGenerateResp::_internal_mutable_chargem() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.chargem_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::CharGem>(GetArena());
    _impl_.chargem_ = reinterpret_cast<::proto::CharGem*>(p);
  }
  return _impl_.chargem_;
}
inline ::proto::CharGem* PROTOBUF_NONNULL CharGemGenerateResp::mutable_chargem()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::CharGem* _msg = _internal_mutable_chargem();
  // @@protoc_insertion_point(field_mutable:proto.CharGemGenerateResp.CharGem)
  return _msg;
}
inline void CharGemGenerateResp::set_allocated_chargem(::proto::CharGem* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.chargem_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.chargem_ = reinterpret_cast<::proto::CharGem*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemGenerateResp.CharGem)
}

// .proto.ChangeInfo ChangeInfo = 2;
inline bool CharGemGenerateResp::has_changeinfo() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.changeinfo_ != nullptr);
  return value;
}
inline const ::proto::ChangeInfo& CharGemGenerateResp::_internal_changeinfo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::ChangeInfo* p = _impl_.changeinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::ChangeInfo&>(::proto::_ChangeInfo_default_instance_);
}
inline const ::proto::ChangeInfo& CharGemGenerateResp::changeinfo() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemGenerateResp.ChangeInfo)
  return _internal_changeinfo();
}
inline void CharGemGenerateResp::unsafe_arena_set_allocated_changeinfo(
    ::proto::ChangeInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.changeinfo_);
  }
  _impl_.changeinfo_ = reinterpret_cast<::proto::ChangeInfo*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.CharGemGenerateResp.ChangeInfo)
}
inline ::proto::ChangeInfo* PROTOBUF_NULLABLE CharGemGenerateResp::release_changeinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::ChangeInfo* released = _impl_.changeinfo_;
  _impl_.changeinfo_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::ChangeInfo* PROTOBUF_NULLABLE CharGemGenerateResp::unsafe_arena_release_changeinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemGenerateResp.ChangeInfo)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::ChangeInfo* temp = _impl_.changeinfo_;
  _impl_.changeinfo_ = nullptr;
  return temp;
}
inline ::proto::ChangeInfo* PROTOBUF_NONNULL CharGemGenerateResp::_internal_mutable_changeinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.changeinfo_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::ChangeInfo>(GetArena());
    _impl_.changeinfo_ = reinterpret_cast<::proto::ChangeInfo*>(p);
  }
  return _impl_.changeinfo_;
}
inline ::proto::ChangeInfo* PROTOBUF_NONNULL CharGemGenerateResp::mutable_changeinfo()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::ChangeInfo* _msg = _internal_mutable_changeinfo();
  // @@protoc_insertion_point(field_mutable:proto.CharGemGenerateResp.ChangeInfo)
  return _msg;
}
inline void CharGemGenerateResp::set_allocated_changeinfo(::proto::ChangeInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.changeinfo_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.changeinfo_ = reinterpret_cast<::proto::ChangeInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemGenerateResp.ChangeInfo)
}

// bytes NextPackage = 2047;
inline void CharGemGenerateResp::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CharGemGenerateResp::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemGenerateResp.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CharGemGenerateResp::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CharGemGenerateResp.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL CharGemGenerateResp::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.CharGemGenerateResp.NextPackage)
  return _s;
}
inline const ::std::string& CharGemGenerateResp::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void CharGemGenerateResp::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CharGemGenerateResp::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CharGemGenerateResp::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemGenerateResp.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void CharGemGenerateResp::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemGenerateResp.NextPackage)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // char_5fgem_5fgenerate_2eproto_2epb_2eh
