// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: char_gem_instance_sweep.proto
// Protobuf C++ Version: 6.33.4

#ifndef char_5fgem_5finstance_5fsweep_2eproto_2epb_2eh
#define char_5fgem_5finstance_5fsweep_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "public.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_char_5fgem_5finstance_5fsweep_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_char_5fgem_5finstance_5fsweep_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_char_5fgem_5finstance_5fsweep_2eproto;
}  // extern "C"
namespace proto {
class CharGemInstanceSweepReq;
struct CharGemInstanceSweepReqDefaultTypeInternal;
extern CharGemInstanceSweepReqDefaultTypeInternal _CharGemInstanceSweepReq_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CharGemInstanceSweepReq_class_data_;
class CharGemInstanceSweepResp;
struct CharGemInstanceSweepRespDefaultTypeInternal;
extern CharGemInstanceSweepRespDefaultTypeInternal _CharGemInstanceSweepResp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CharGemInstanceSweepResp_class_data_;
class CharGemInstanceSweepReward;
struct CharGemInstanceSweepRewardDefaultTypeInternal;
extern CharGemInstanceSweepRewardDefaultTypeInternal _CharGemInstanceSweepReward_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CharGemInstanceSweepReward_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class CharGemInstanceSweepReward final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CharGemInstanceSweepReward) */ {
 public:
  inline CharGemInstanceSweepReward() : CharGemInstanceSweepReward(nullptr) {}
  ~CharGemInstanceSweepReward() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CharGemInstanceSweepReward* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CharGemInstanceSweepReward));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CharGemInstanceSweepReward(::google::protobuf::internal::ConstantInitialized);

  inline CharGemInstanceSweepReward(const CharGemInstanceSweepReward& from) : CharGemInstanceSweepReward(nullptr, from) {}
  inline CharGemInstanceSweepReward(CharGemInstanceSweepReward&& from) noexcept
      : CharGemInstanceSweepReward(nullptr, ::std::move(from)) {}
  inline CharGemInstanceSweepReward& operator=(const CharGemInstanceSweepReward& from) {
    CopyFrom(from);
    return *this;
  }
  inline CharGemInstanceSweepReward& operator=(CharGemInstanceSweepReward&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CharGemInstanceSweepReward& default_instance() {
    return *reinterpret_cast<const CharGemInstanceSweepReward*>(
        &_CharGemInstanceSweepReward_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CharGemInstanceSweepReward& a, CharGemInstanceSweepReward& b) { a.Swap(&b); }
  inline void Swap(CharGemInstanceSweepReward* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CharGemInstanceSweepReward* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CharGemInstanceSweepReward* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CharGemInstanceSweepReward>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CharGemInstanceSweepReward& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CharGemInstanceSweepReward& from) { CharGemInstanceSweepReward::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CharGemInstanceSweepReward* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CharGemInstanceSweepReward"; }

  explicit CharGemInstanceSweepReward(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CharGemInstanceSweepReward(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CharGemInstanceSweepReward& from);
  CharGemInstanceSweepReward(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CharGemInstanceSweepReward&& from) noexcept
      : CharGemInstanceSweepReward(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAwardItemsFieldNumber = 1,
    kDoubleItemsFieldNumber = 3,
    kNextPackageFieldNumber = 2047,
    kExpFieldNumber = 2,
  };
  // repeated .proto.ItemTpl AwardItems = 1;
  int awarditems_size() const;
  private:
  int _internal_awarditems_size() const;

  public:
  void clear_awarditems() ;
  ::proto::ItemTpl* PROTOBUF_NONNULL mutable_awarditems(int index);
  ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>* PROTOBUF_NONNULL mutable_awarditems();

  private:
  const ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>& _internal_awarditems() const;
  ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>* PROTOBUF_NONNULL _internal_mutable_awarditems();
  public:
  const ::proto::ItemTpl& awarditems(int index) const;
  ::proto::ItemTpl* PROTOBUF_NONNULL add_awarditems();
  const ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>& awarditems() const;
  // repeated .proto.ItemTpl DoubleItems = 3;
  int doubleitems_size() const;
  private:
  int _internal_doubleitems_size() const;

  public:
  void clear_doubleitems() ;
  ::proto::ItemTpl* PROTOBUF_NONNULL mutable_doubleitems(int index);
  ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>* PROTOBUF_NONNULL mutable_doubleitems();

  private:
  const ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>& _internal_doubleitems() const;
  ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>* PROTOBUF_NONNULL _internal_mutable_doubleitems();
  public:
  const ::proto::ItemTpl& doubleitems(int index) const;
  ::proto::ItemTpl* PROTOBUF_NONNULL add_doubleitems();
  const ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>& doubleitems() const;
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // uint32 Exp = 2;
  void clear_exp() ;
  ::uint32_t exp() const;
  void set_exp(::uint32_t value);

  private:
  ::uint32_t _internal_exp() const;
  void _internal_set_exp(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.CharGemInstanceSweepReward)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 4,
                                   2, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CharGemInstanceSweepReward& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::proto::ItemTpl > awarditems_;
    ::google::protobuf::RepeatedPtrField< ::proto::ItemTpl > doubleitems_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    ::uint32_t exp_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_char_5fgem_5finstance_5fsweep_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CharGemInstanceSweepReward_class_data_;
// -------------------------------------------------------------------

class CharGemInstanceSweepResp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CharGemInstanceSweepResp) */ {
 public:
  inline CharGemInstanceSweepResp() : CharGemInstanceSweepResp(nullptr) {}
  ~CharGemInstanceSweepResp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CharGemInstanceSweepResp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CharGemInstanceSweepResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CharGemInstanceSweepResp(::google::protobuf::internal::ConstantInitialized);

  inline CharGemInstanceSweepResp(const CharGemInstanceSweepResp& from) : CharGemInstanceSweepResp(nullptr, from) {}
  inline CharGemInstanceSweepResp(CharGemInstanceSweepResp&& from) noexcept
      : CharGemInstanceSweepResp(nullptr, ::std::move(from)) {}
  inline CharGemInstanceSweepResp& operator=(const CharGemInstanceSweepResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline CharGemInstanceSweepResp& operator=(CharGemInstanceSweepResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CharGemInstanceSweepResp& default_instance() {
    return *reinterpret_cast<const CharGemInstanceSweepResp*>(
        &_CharGemInstanceSweepResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CharGemInstanceSweepResp& a, CharGemInstanceSweepResp& b) { a.Swap(&b); }
  inline void Swap(CharGemInstanceSweepResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CharGemInstanceSweepResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CharGemInstanceSweepResp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CharGemInstanceSweepResp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CharGemInstanceSweepResp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CharGemInstanceSweepResp& from) { CharGemInstanceSweepResp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CharGemInstanceSweepResp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CharGemInstanceSweepResp"; }

  explicit CharGemInstanceSweepResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CharGemInstanceSweepResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CharGemInstanceSweepResp& from);
  CharGemInstanceSweepResp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CharGemInstanceSweepResp&& from) noexcept
      : CharGemInstanceSweepResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRewardsFieldNumber = 2,
    kNextPackageFieldNumber = 2047,
    kChangeFieldNumber = 1,
  };
  // repeated .proto.CharGemInstanceSweepReward Rewards = 2;
  int rewards_size() const;
  private:
  int _internal_rewards_size() const;

  public:
  void clear_rewards() ;
  ::proto::CharGemInstanceSweepReward* PROTOBUF_NONNULL mutable_rewards(int index);
  ::google::protobuf::RepeatedPtrField<::proto::CharGemInstanceSweepReward>* PROTOBUF_NONNULL mutable_rewards();

  private:
  const ::google::protobuf::RepeatedPtrField<::proto::CharGemInstanceSweepReward>& _internal_rewards() const;
  ::google::protobuf::RepeatedPtrField<::proto::CharGemInstanceSweepReward>* PROTOBUF_NONNULL _internal_mutable_rewards();
  public:
  const ::proto::CharGemInstanceSweepReward& rewards(int index) const;
  ::proto::CharGemInstanceSweepReward* PROTOBUF_NONNULL add_rewards();
  const ::google::protobuf::RepeatedPtrField<::proto::CharGemInstanceSweepReward>& rewards() const;
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // .proto.ChangeInfo Change = 1;
  bool has_change() const;
  void clear_change() ;
  const ::proto::ChangeInfo& change() const;
  [[nodiscard]] ::proto::ChangeInfo* PROTOBUF_NULLABLE release_change();
  ::proto::ChangeInfo* PROTOBUF_NONNULL mutable_change();
  void set_allocated_change(::proto::ChangeInfo* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_change(::proto::ChangeInfo* PROTOBUF_NULLABLE value);
  ::proto::ChangeInfo* PROTOBUF_NULLABLE unsafe_arena_release_change();

  private:
  const ::proto::ChangeInfo& _internal_change() const;
  ::proto::ChangeInfo* PROTOBUF_NONNULL _internal_mutable_change();

  public:
  // @@protoc_insertion_point(class_scope:proto.CharGemInstanceSweepResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   2, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CharGemInstanceSweepResp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::proto::CharGemInstanceSweepReward > rewards_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    ::proto::ChangeInfo* PROTOBUF_NULLABLE change_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_char_5fgem_5finstance_5fsweep_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CharGemInstanceSweepResp_class_data_;
// -------------------------------------------------------------------

class CharGemInstanceSweepReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CharGemInstanceSweepReq) */ {
 public:
  inline CharGemInstanceSweepReq() : CharGemInstanceSweepReq(nullptr) {}
  ~CharGemInstanceSweepReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CharGemInstanceSweepReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CharGemInstanceSweepReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CharGemInstanceSweepReq(::google::protobuf::internal::ConstantInitialized);

  inline CharGemInstanceSweepReq(const CharGemInstanceSweepReq& from) : CharGemInstanceSweepReq(nullptr, from) {}
  inline CharGemInstanceSweepReq(CharGemInstanceSweepReq&& from) noexcept
      : CharGemInstanceSweepReq(nullptr, ::std::move(from)) {}
  inline CharGemInstanceSweepReq& operator=(const CharGemInstanceSweepReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CharGemInstanceSweepReq& operator=(CharGemInstanceSweepReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CharGemInstanceSweepReq& default_instance() {
    return *reinterpret_cast<const CharGemInstanceSweepReq*>(
        &_CharGemInstanceSweepReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CharGemInstanceSweepReq& a, CharGemInstanceSweepReq& b) { a.Swap(&b); }
  inline void Swap(CharGemInstanceSweepReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CharGemInstanceSweepReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CharGemInstanceSweepReq* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CharGemInstanceSweepReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CharGemInstanceSweepReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CharGemInstanceSweepReq& from) { CharGemInstanceSweepReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CharGemInstanceSweepReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CharGemInstanceSweepReq"; }

  explicit CharGemInstanceSweepReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CharGemInstanceSweepReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CharGemInstanceSweepReq& from);
  CharGemInstanceSweepReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CharGemInstanceSweepReq&& from) noexcept
      : CharGemInstanceSweepReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextPackageFieldNumber = 2047,
    kEventsFieldNumber = 15,
    kIdFieldNumber = 1,
    kTimesFieldNumber = 2,
  };
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // .proto.Events Events = 15;
  bool has_events() const;
  void clear_events() ;
  const ::proto::Events& events() const;
  [[nodiscard]] ::proto::Events* PROTOBUF_NULLABLE release_events();
  ::proto::Events* PROTOBUF_NONNULL mutable_events();
  void set_allocated_events(::proto::Events* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_events(::proto::Events* PROTOBUF_NULLABLE value);
  ::proto::Events* PROTOBUF_NULLABLE unsafe_arena_release_events();

  private:
  const ::proto::Events& _internal_events() const;
  ::proto::Events* PROTOBUF_NONNULL _internal_mutable_events();

  public:
  // uint32 Id = 1;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // uint32 Times = 2;
  void clear_times() ;
  ::uint32_t times() const;
  void set_times(::uint32_t value);

  private:
  ::uint32_t _internal_times() const;
  void _internal_set_times(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.CharGemInstanceSweepReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CharGemInstanceSweepReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    ::proto::Events* PROTOBUF_NULLABLE events_;
    ::uint32_t id_;
    ::uint32_t times_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_char_5fgem_5finstance_5fsweep_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CharGemInstanceSweepReq_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CharGemInstanceSweepReq

// uint32 Id = 1;
inline void CharGemInstanceSweepReq::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t CharGemInstanceSweepReq::id() const {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepReq.Id)
  return _internal_id();
}
inline void CharGemInstanceSweepReq::set_id(::uint32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.CharGemInstanceSweepReq.Id)
}
inline ::uint32_t CharGemInstanceSweepReq::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void CharGemInstanceSweepReq::_internal_set_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// uint32 Times = 2;
inline void CharGemInstanceSweepReq::clear_times() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.times_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t CharGemInstanceSweepReq::times() const {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepReq.Times)
  return _internal_times();
}
inline void CharGemInstanceSweepReq::set_times(::uint32_t value) {
  _internal_set_times(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:proto.CharGemInstanceSweepReq.Times)
}
inline ::uint32_t CharGemInstanceSweepReq::_internal_times() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.times_;
}
inline void CharGemInstanceSweepReq::_internal_set_times(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.times_ = value;
}

// .proto.Events Events = 15;
inline bool CharGemInstanceSweepReq::has_events() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.events_ != nullptr);
  return value;
}
inline const ::proto::Events& CharGemInstanceSweepReq::_internal_events() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::Events* p = _impl_.events_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::Events&>(::proto::_Events_default_instance_);
}
inline const ::proto::Events& CharGemInstanceSweepReq::events() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepReq.Events)
  return _internal_events();
}
inline void CharGemInstanceSweepReq::unsafe_arena_set_allocated_events(
    ::proto::Events* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.events_);
  }
  _impl_.events_ = reinterpret_cast<::proto::Events*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.CharGemInstanceSweepReq.Events)
}
inline ::proto::Events* PROTOBUF_NULLABLE CharGemInstanceSweepReq::release_events() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::Events* released = _impl_.events_;
  _impl_.events_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::Events* PROTOBUF_NULLABLE CharGemInstanceSweepReq::unsafe_arena_release_events() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemInstanceSweepReq.Events)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::Events* temp = _impl_.events_;
  _impl_.events_ = nullptr;
  return temp;
}
inline ::proto::Events* PROTOBUF_NONNULL CharGemInstanceSweepReq::_internal_mutable_events() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.events_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::Events>(GetArena());
    _impl_.events_ = reinterpret_cast<::proto::Events*>(p);
  }
  return _impl_.events_;
}
inline ::proto::Events* PROTOBUF_NONNULL CharGemInstanceSweepReq::mutable_events()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::Events* _msg = _internal_mutable_events();
  // @@protoc_insertion_point(field_mutable:proto.CharGemInstanceSweepReq.Events)
  return _msg;
}
inline void CharGemInstanceSweepReq::set_allocated_events(::proto::Events* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.events_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.events_ = reinterpret_cast<::proto::Events*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemInstanceSweepReq.Events)
}

// bytes NextPackage = 2047;
inline void CharGemInstanceSweepReq::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CharGemInstanceSweepReq::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepReq.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CharGemInstanceSweepReq::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CharGemInstanceSweepReq.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL CharGemInstanceSweepReq::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.CharGemInstanceSweepReq.NextPackage)
  return _s;
}
inline const ::std::string& CharGemInstanceSweepReq::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void CharGemInstanceSweepReq::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CharGemInstanceSweepReq::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CharGemInstanceSweepReq::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemInstanceSweepReq.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void CharGemInstanceSweepReq::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemInstanceSweepReq.NextPackage)
}

// -------------------------------------------------------------------

// CharGemInstanceSweepReward

// repeated .proto.ItemTpl AwardItems = 1;
inline int CharGemInstanceSweepReward::_internal_awarditems_size() const {
  return _internal_awarditems().size();
}
inline int CharGemInstanceSweepReward::awarditems_size() const {
  return _internal_awarditems_size();
}
inline ::proto::ItemTpl* PROTOBUF_NONNULL CharGemInstanceSweepReward::mutable_awarditems(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:proto.CharGemInstanceSweepReward.AwardItems)
  return _internal_mutable_awarditems()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>* PROTOBUF_NONNULL CharGemInstanceSweepReward::mutable_awarditems()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:proto.CharGemInstanceSweepReward.AwardItems)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_awarditems();
}
inline const ::proto::ItemTpl& CharGemInstanceSweepReward::awarditems(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepReward.AwardItems)
  return _internal_awarditems().Get(index);
}
inline ::proto::ItemTpl* PROTOBUF_NONNULL CharGemInstanceSweepReward::add_awarditems()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::proto::ItemTpl* _add =
      _internal_mutable_awarditems()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:proto.CharGemInstanceSweepReward.AwardItems)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>& CharGemInstanceSweepReward::awarditems() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.CharGemInstanceSweepReward.AwardItems)
  return _internal_awarditems();
}
inline const ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>&
CharGemInstanceSweepReward::_internal_awarditems() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.awarditems_;
}
inline ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>* PROTOBUF_NONNULL
CharGemInstanceSweepReward::_internal_mutable_awarditems() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.awarditems_;
}

// uint32 Exp = 2;
inline void CharGemInstanceSweepReward::clear_exp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exp_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t CharGemInstanceSweepReward::exp() const {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepReward.Exp)
  return _internal_exp();
}
inline void CharGemInstanceSweepReward::set_exp(::uint32_t value) {
  _internal_set_exp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:proto.CharGemInstanceSweepReward.Exp)
}
inline ::uint32_t CharGemInstanceSweepReward::_internal_exp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exp_;
}
inline void CharGemInstanceSweepReward::_internal_set_exp(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exp_ = value;
}

// repeated .proto.ItemTpl DoubleItems = 3;
inline int CharGemInstanceSweepReward::_internal_doubleitems_size() const {
  return _internal_doubleitems().size();
}
inline int CharGemInstanceSweepReward::doubleitems_size() const {
  return _internal_doubleitems_size();
}
inline ::proto::ItemTpl* PROTOBUF_NONNULL CharGemInstanceSweepReward::mutable_doubleitems(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:proto.CharGemInstanceSweepReward.DoubleItems)
  return _internal_mutable_doubleitems()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>* PROTOBUF_NONNULL CharGemInstanceSweepReward::mutable_doubleitems()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:proto.CharGemInstanceSweepReward.DoubleItems)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_doubleitems();
}
inline const ::proto::ItemTpl& CharGemInstanceSweepReward::doubleitems(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepReward.DoubleItems)
  return _internal_doubleitems().Get(index);
}
inline ::proto::ItemTpl* PROTOBUF_NONNULL CharGemInstanceSweepReward::add_doubleitems()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::proto::ItemTpl* _add =
      _internal_mutable_doubleitems()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:proto.CharGemInstanceSweepReward.DoubleItems)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>& CharGemInstanceSweepReward::doubleitems() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.CharGemInstanceSweepReward.DoubleItems)
  return _internal_doubleitems();
}
inline const ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>&
CharGemInstanceSweepReward::_internal_doubleitems() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.doubleitems_;
}
inline ::google::protobuf::RepeatedPtrField<::proto::ItemTpl>* PROTOBUF_NONNULL
CharGemInstanceSweepReward::_internal_mutable_doubleitems() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.doubleitems_;
}

// bytes NextPackage = 2047;
inline void CharGemInstanceSweepReward::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& CharGemInstanceSweepReward::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepReward.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CharGemInstanceSweepReward::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CharGemInstanceSweepReward.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL CharGemInstanceSweepReward::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.CharGemInstanceSweepReward.NextPackage)
  return _s;
}
inline const ::std::string& CharGemInstanceSweepReward::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void CharGemInstanceSweepReward::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CharGemInstanceSweepReward::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CharGemInstanceSweepReward::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemInstanceSweepReward.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void CharGemInstanceSweepReward::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemInstanceSweepReward.NextPackage)
}

// -------------------------------------------------------------------

// CharGemInstanceSweepResp

// .proto.ChangeInfo Change = 1;
inline bool CharGemInstanceSweepResp::has_change() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.change_ != nullptr);
  return value;
}
inline const ::proto::ChangeInfo& CharGemInstanceSweepResp::_internal_change() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::ChangeInfo* p = _impl_.change_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::ChangeInfo&>(::proto::_ChangeInfo_default_instance_);
}
inline const ::proto::ChangeInfo& CharGemInstanceSweepResp::change() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepResp.Change)
  return _internal_change();
}
inline void CharGemInstanceSweepResp::unsafe_arena_set_allocated_change(
    ::proto::ChangeInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.change_);
  }
  _impl_.change_ = reinterpret_cast<::proto::ChangeInfo*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.CharGemInstanceSweepResp.Change)
}
inline ::proto::ChangeInfo* PROTOBUF_NULLABLE CharGemInstanceSweepResp::release_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::ChangeInfo* released = _impl_.change_;
  _impl_.change_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::ChangeInfo* PROTOBUF_NULLABLE CharGemInstanceSweepResp::unsafe_arena_release_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemInstanceSweepResp.Change)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::ChangeInfo* temp = _impl_.change_;
  _impl_.change_ = nullptr;
  return temp;
}
inline ::proto::ChangeInfo* PROTOBUF_NONNULL CharGemInstanceSweepResp::_internal_mutable_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.change_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::ChangeInfo>(GetArena());
    _impl_.change_ = reinterpret_cast<::proto::ChangeInfo*>(p);
  }
  return _impl_.change_;
}
inline ::proto::ChangeInfo* PROTOBUF_NONNULL CharGemInstanceSweepResp::mutable_change()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::proto::ChangeInfo* _msg = _internal_mutable_change();
  // @@protoc_insertion_point(field_mutable:proto.CharGemInstanceSweepResp.Change)
  return _msg;
}
inline void CharGemInstanceSweepResp::set_allocated_change(::proto::ChangeInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.change_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.change_ = reinterpret_cast<::proto::ChangeInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemInstanceSweepResp.Change)
}

// repeated .proto.CharGemInstanceSweepReward Rewards = 2;
inline int CharGemInstanceSweepResp::_internal_rewards_size() const {
  return _internal_rewards().size();
}
inline int CharGemInstanceSweepResp::rewards_size() const {
  return _internal_rewards_size();
}
inline void CharGemInstanceSweepResp::clear_rewards() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rewards_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::proto::CharGemInstanceSweepReward* PROTOBUF_NONNULL CharGemInstanceSweepResp::mutable_rewards(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:proto.CharGemInstanceSweepResp.Rewards)
  return _internal_mutable_rewards()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::proto::CharGemInstanceSweepReward>* PROTOBUF_NONNULL CharGemInstanceSweepResp::mutable_rewards()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:proto.CharGemInstanceSweepResp.Rewards)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rewards();
}
inline const ::proto::CharGemInstanceSweepReward& CharGemInstanceSweepResp::rewards(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepResp.Rewards)
  return _internal_rewards().Get(index);
}
inline ::proto::CharGemInstanceSweepReward* PROTOBUF_NONNULL CharGemInstanceSweepResp::add_rewards()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::proto::CharGemInstanceSweepReward* _add =
      _internal_mutable_rewards()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:proto.CharGemInstanceSweepResp.Rewards)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::proto::CharGemInstanceSweepReward>& CharGemInstanceSweepResp::rewards() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.CharGemInstanceSweepResp.Rewards)
  return _internal_rewards();
}
inline const ::google::protobuf::RepeatedPtrField<::proto::CharGemInstanceSweepReward>&
CharGemInstanceSweepResp::_internal_rewards() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rewards_;
}
inline ::google::protobuf::RepeatedPtrField<::proto::CharGemInstanceSweepReward>* PROTOBUF_NONNULL
CharGemInstanceSweepResp::_internal_mutable_rewards() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rewards_;
}

// bytes NextPackage = 2047;
inline void CharGemInstanceSweepResp::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& CharGemInstanceSweepResp::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CharGemInstanceSweepResp.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CharGemInstanceSweepResp::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CharGemInstanceSweepResp.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL CharGemInstanceSweepResp::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.CharGemInstanceSweepResp.NextPackage)
  return _s;
}
inline const ::std::string& CharGemInstanceSweepResp::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void CharGemInstanceSweepResp::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CharGemInstanceSweepResp::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CharGemInstanceSweepResp::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CharGemInstanceSweepResp.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void CharGemInstanceSweepResp::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CharGemInstanceSweepResp.NextPackage)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // char_5fgem_5finstance_5fsweep_2eproto_2epb_2eh
