// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: disc_limit_break.proto
// Protobuf C++ Version: 6.33.4

#ifndef disc_5flimit_5fbreak_2eproto_2epb_2eh
#define disc_5flimit_5fbreak_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "public.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_disc_5flimit_5fbreak_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_disc_5flimit_5fbreak_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_disc_5flimit_5fbreak_2eproto;
}  // extern "C"
namespace proto {
class DiscLimitBreakReq;
struct DiscLimitBreakReqDefaultTypeInternal;
extern DiscLimitBreakReqDefaultTypeInternal _DiscLimitBreakReq_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DiscLimitBreakReq_class_data_;
class DiscLimitBreakResp;
struct DiscLimitBreakRespDefaultTypeInternal;
extern DiscLimitBreakRespDefaultTypeInternal _DiscLimitBreakResp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull DiscLimitBreakResp_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class DiscLimitBreakReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.DiscLimitBreakReq) */ {
 public:
  inline DiscLimitBreakReq() : DiscLimitBreakReq(nullptr) {}
  ~DiscLimitBreakReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DiscLimitBreakReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DiscLimitBreakReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DiscLimitBreakReq(::google::protobuf::internal::ConstantInitialized);

  inline DiscLimitBreakReq(const DiscLimitBreakReq& from) : DiscLimitBreakReq(nullptr, from) {}
  inline DiscLimitBreakReq(DiscLimitBreakReq&& from) noexcept
      : DiscLimitBreakReq(nullptr, ::std::move(from)) {}
  inline DiscLimitBreakReq& operator=(const DiscLimitBreakReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiscLimitBreakReq& operator=(DiscLimitBreakReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiscLimitBreakReq& default_instance() {
    return *reinterpret_cast<const DiscLimitBreakReq*>(
        &_DiscLimitBreakReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DiscLimitBreakReq& a, DiscLimitBreakReq& b) { a.Swap(&b); }
  inline void Swap(DiscLimitBreakReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiscLimitBreakReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiscLimitBreakReq* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DiscLimitBreakReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DiscLimitBreakReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DiscLimitBreakReq& from) { DiscLimitBreakReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DiscLimitBreakReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.DiscLimitBreakReq"; }

  explicit DiscLimitBreakReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DiscLimitBreakReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DiscLimitBreakReq& from);
  DiscLimitBreakReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DiscLimitBreakReq&& from) noexcept
      : DiscLimitBreakReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextPackageFieldNumber = 2047,
    kIdFieldNumber = 1,
    kQtyFieldNumber = 2,
  };
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // uint32 Id = 1;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // uint32 Qty = 2;
  void clear_qty() ;
  ::uint32_t qty() const;
  void set_qty(::uint32_t value);

  private:
  ::uint32_t _internal_qty() const;
  void _internal_set_qty(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.DiscLimitBreakReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DiscLimitBreakReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    ::uint32_t id_;
    ::uint32_t qty_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_disc_5flimit_5fbreak_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DiscLimitBreakReq_class_data_;
// -------------------------------------------------------------------

class DiscLimitBreakResp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.DiscLimitBreakResp) */ {
 public:
  inline DiscLimitBreakResp() : DiscLimitBreakResp(nullptr) {}
  ~DiscLimitBreakResp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DiscLimitBreakResp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DiscLimitBreakResp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DiscLimitBreakResp(::google::protobuf::internal::ConstantInitialized);

  inline DiscLimitBreakResp(const DiscLimitBreakResp& from) : DiscLimitBreakResp(nullptr, from) {}
  inline DiscLimitBreakResp(DiscLimitBreakResp&& from) noexcept
      : DiscLimitBreakResp(nullptr, ::std::move(from)) {}
  inline DiscLimitBreakResp& operator=(const DiscLimitBreakResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiscLimitBreakResp& operator=(DiscLimitBreakResp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiscLimitBreakResp& default_instance() {
    return *reinterpret_cast<const DiscLimitBreakResp*>(
        &_DiscLimitBreakResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(DiscLimitBreakResp& a, DiscLimitBreakResp& b) { a.Swap(&b); }
  inline void Swap(DiscLimitBreakResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiscLimitBreakResp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiscLimitBreakResp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DiscLimitBreakResp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DiscLimitBreakResp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DiscLimitBreakResp& from) { DiscLimitBreakResp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DiscLimitBreakResp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.DiscLimitBreakResp"; }

  explicit DiscLimitBreakResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  DiscLimitBreakResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const DiscLimitBreakResp& from);
  DiscLimitBreakResp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, DiscLimitBreakResp&& from) noexcept
      : DiscLimitBreakResp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextPackageFieldNumber = 2047,
    kChangeFieldNumber = 2,
    kStarFieldNumber = 1,
  };
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // .proto.ChangeInfo Change = 2;
  bool has_change() const;
  void clear_change() ;
  const ::proto::ChangeInfo& change() const;
  [[nodiscard]] ::proto::ChangeInfo* PROTOBUF_NULLABLE release_change();
  ::proto::ChangeInfo* PROTOBUF_NONNULL mutable_change();
  void set_allocated_change(::proto::ChangeInfo* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_change(::proto::ChangeInfo* PROTOBUF_NULLABLE value);
  ::proto::ChangeInfo* PROTOBUF_NULLABLE unsafe_arena_release_change();

  private:
  const ::proto::ChangeInfo& _internal_change() const;
  ::proto::ChangeInfo* PROTOBUF_NONNULL _internal_mutable_change();

  public:
  // uint32 Star = 1;
  void clear_star() ;
  ::uint32_t star() const;
  void set_star(::uint32_t value);

  private:
  ::uint32_t _internal_star() const;
  void _internal_set_star(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.DiscLimitBreakResp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const DiscLimitBreakResp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    ::proto::ChangeInfo* PROTOBUF_NULLABLE change_;
    ::uint32_t star_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_disc_5flimit_5fbreak_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull DiscLimitBreakResp_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DiscLimitBreakReq

// uint32 Id = 1;
inline void DiscLimitBreakReq::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t DiscLimitBreakReq::id() const {
  // @@protoc_insertion_point(field_get:proto.DiscLimitBreakReq.Id)
  return _internal_id();
}
inline void DiscLimitBreakReq::set_id(::uint32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.DiscLimitBreakReq.Id)
}
inline ::uint32_t DiscLimitBreakReq::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void DiscLimitBreakReq::_internal_set_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// uint32 Qty = 2;
inline void DiscLimitBreakReq::clear_qty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qty_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t DiscLimitBreakReq::qty() const {
  // @@protoc_insertion_point(field_get:proto.DiscLimitBreakReq.Qty)
  return _internal_qty();
}
inline void DiscLimitBreakReq::set_qty(::uint32_t value) {
  _internal_set_qty(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.DiscLimitBreakReq.Qty)
}
inline ::uint32_t DiscLimitBreakReq::_internal_qty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qty_;
}
inline void DiscLimitBreakReq::_internal_set_qty(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qty_ = value;
}

// bytes NextPackage = 2047;
inline void DiscLimitBreakReq::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& DiscLimitBreakReq::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.DiscLimitBreakReq.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void DiscLimitBreakReq::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.DiscLimitBreakReq.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL DiscLimitBreakReq::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.DiscLimitBreakReq.NextPackage)
  return _s;
}
inline const ::std::string& DiscLimitBreakReq::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void DiscLimitBreakReq::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL DiscLimitBreakReq::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE DiscLimitBreakReq::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.DiscLimitBreakReq.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void DiscLimitBreakReq::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.DiscLimitBreakReq.NextPackage)
}

// -------------------------------------------------------------------

// DiscLimitBreakResp

// uint32 Star = 1;
inline void DiscLimitBreakResp::clear_star() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.star_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t DiscLimitBreakResp::star() const {
  // @@protoc_insertion_point(field_get:proto.DiscLimitBreakResp.Star)
  return _internal_star();
}
inline void DiscLimitBreakResp::set_star(::uint32_t value) {
  _internal_set_star(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.DiscLimitBreakResp.Star)
}
inline ::uint32_t DiscLimitBreakResp::_internal_star() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.star_;
}
inline void DiscLimitBreakResp::_internal_set_star(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.star_ = value;
}

// .proto.ChangeInfo Change = 2;
inline bool DiscLimitBreakResp::has_change() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.change_ != nullptr);
  return value;
}
inline const ::proto::ChangeInfo& DiscLimitBreakResp::_internal_change() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::ChangeInfo* p = _impl_.change_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::ChangeInfo&>(::proto::_ChangeInfo_default_instance_);
}
inline const ::proto::ChangeInfo& DiscLimitBreakResp::change() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.DiscLimitBreakResp.Change)
  return _internal_change();
}
inline void DiscLimitBreakResp::unsafe_arena_set_allocated_change(
    ::proto::ChangeInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.change_);
  }
  _impl_.change_ = reinterpret_cast<::proto::ChangeInfo*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.DiscLimitBreakResp.Change)
}
inline ::proto::ChangeInfo* PROTOBUF_NULLABLE DiscLimitBreakResp::release_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::ChangeInfo* released = _impl_.change_;
  _impl_.change_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::ChangeInfo* PROTOBUF_NULLABLE DiscLimitBreakResp::unsafe_arena_release_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.DiscLimitBreakResp.Change)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::ChangeInfo* temp = _impl_.change_;
  _impl_.change_ = nullptr;
  return temp;
}
inline ::proto::ChangeInfo* PROTOBUF_NONNULL DiscLimitBreakResp::_internal_mutable_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.change_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::ChangeInfo>(GetArena());
    _impl_.change_ = reinterpret_cast<::proto::ChangeInfo*>(p);
  }
  return _impl_.change_;
}
inline ::proto::ChangeInfo* PROTOBUF_NONNULL DiscLimitBreakResp::mutable_change()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::ChangeInfo* _msg = _internal_mutable_change();
  // @@protoc_insertion_point(field_mutable:proto.DiscLimitBreakResp.Change)
  return _msg;
}
inline void DiscLimitBreakResp::set_allocated_change(::proto::ChangeInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.change_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.change_ = reinterpret_cast<::proto::ChangeInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.DiscLimitBreakResp.Change)
}

// bytes NextPackage = 2047;
inline void DiscLimitBreakResp::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& DiscLimitBreakResp::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.DiscLimitBreakResp.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void DiscLimitBreakResp::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.DiscLimitBreakResp.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL DiscLimitBreakResp::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.DiscLimitBreakResp.NextPackage)
  return _s;
}
inline const ::std::string& DiscLimitBreakResp::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void DiscLimitBreakResp::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL DiscLimitBreakResp::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE DiscLimitBreakResp::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.DiscLimitBreakResp.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void DiscLimitBreakResp::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.DiscLimitBreakResp.NextPackage)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // disc_5flimit_5fbreak_2eproto_2epb_2eh
