// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: joint_drill_2_settle.proto
// Protobuf C++ Version: 6.33.4

#include "joint_drill_2_settle.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr JointDrill2SettleReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sample_{nullptr},
        events_{nullptr},
        time_{0u},
        damage_{0u},
        checksum_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR JointDrill2SettleReq::JointDrill2SettleReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(JointDrill2SettleReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JointDrill2SettleReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JointDrill2SettleReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JointDrill2SettleReqDefaultTypeInternal() {}
  union {
    JointDrill2SettleReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JointDrill2SettleReqDefaultTypeInternal _JointDrill2SettleReq_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_joint_5fdrill_5f2_5fsettle_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_joint_5fdrill_5f2_5fsettle_2eproto = nullptr;
const ::uint32_t
    TableStruct_joint_5fdrill_5f2_5fsettle_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::JointDrill2SettleReq, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::JointDrill2SettleReq, _impl_.time_),
        PROTOBUF_FIELD_OFFSET(::proto::JointDrill2SettleReq, _impl_.damage_),
        PROTOBUF_FIELD_OFFSET(::proto::JointDrill2SettleReq, _impl_.sample_),
        PROTOBUF_FIELD_OFFSET(::proto::JointDrill2SettleReq, _impl_.checksum_),
        PROTOBUF_FIELD_OFFSET(::proto::JointDrill2SettleReq, _impl_.events_),
        PROTOBUF_FIELD_OFFSET(::proto::JointDrill2SettleReq, _impl_.nextpackage_),
        3,
        4,
        1,
        5,
        2,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::JointDrill2SettleReq)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_JointDrill2SettleReq_default_instance_._instance,
};
const char descriptor_table_protodef_joint_5fdrill_5f2_5fsettle_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032joint_drill_2_settle.proto\022\005proto\032\014pub"
    "lic.proto\032\030public_joint_drill.proto\032\037tra"
    "veler_duel_rank_upload.proto\"\255\001\n\024JointDr"
    "ill2SettleReq\022\014\n\004Time\030\001 \001(\r\022\016\n\006Damage\030\002 "
    "\001(\r\0220\n\006Sample\030\003 \001(\0132 .proto.TravelerDuel"
    "BattleSamples\022\020\n\010Checksum\030\004 \001(\004\022\035\n\006Event"
    "s\030\007 \001(\0132\r.proto.Events\022\024\n\013NextPackage\030\377\017"
    " \001(\014b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_joint_5fdrill_5f2_5fsettle_2eproto_deps[3] = {
        &::descriptor_table_public_2eproto,
        &::descriptor_table_public_5fjoint_5fdrill_2eproto,
        &::descriptor_table_traveler_5fduel_5frank_5fupload_2eproto,
};
static ::absl::once_flag descriptor_table_joint_5fdrill_5f2_5fsettle_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_joint_5fdrill_5f2_5fsettle_2eproto = {
    false,
    false,
    292,
    descriptor_table_protodef_joint_5fdrill_5f2_5fsettle_2eproto,
    "joint_drill_2_settle.proto",
    &descriptor_table_joint_5fdrill_5f2_5fsettle_2eproto_once,
    descriptor_table_joint_5fdrill_5f2_5fsettle_2eproto_deps,
    3,
    1,
    schemas,
    file_default_instances,
    TableStruct_joint_5fdrill_5f2_5fsettle_2eproto::offsets,
    file_level_enum_descriptors_joint_5fdrill_5f2_5fsettle_2eproto,
    file_level_service_descriptors_joint_5fdrill_5f2_5fsettle_2eproto,
};
namespace proto {
// ===================================================================

class JointDrill2SettleReq::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<JointDrill2SettleReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_._has_bits_);
};

void JointDrill2SettleReq::clear_sample() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.sample_ != nullptr) _impl_.sample_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void JointDrill2SettleReq::clear_events() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.events_ != nullptr) _impl_.events_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
JointDrill2SettleReq::JointDrill2SettleReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, JointDrill2SettleReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.JointDrill2SettleReq)
}
PROTOBUF_NDEBUG_INLINE JointDrill2SettleReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::JointDrill2SettleReq& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nextpackage_(arena, from.nextpackage_) {}

JointDrill2SettleReq::JointDrill2SettleReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const JointDrill2SettleReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, JointDrill2SettleReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JointDrill2SettleReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.sample_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.sample_)
                : nullptr;
  _impl_.events_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.events_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, time_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, time_),
           offsetof(Impl_, checksum_) -
               offsetof(Impl_, time_) +
               sizeof(Impl_::checksum_));

  // @@protoc_insertion_point(copy_constructor:proto.JointDrill2SettleReq)
}
PROTOBUF_NDEBUG_INLINE JointDrill2SettleReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nextpackage_(arena) {}

inline void JointDrill2SettleReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, sample_),
           0,
           offsetof(Impl_, checksum_) -
               offsetof(Impl_, sample_) +
               sizeof(Impl_::checksum_));
}
JointDrill2SettleReq::~JointDrill2SettleReq() {
  // @@protoc_insertion_point(destructor:proto.JointDrill2SettleReq)
  SharedDtor(*this);
}
inline void JointDrill2SettleReq::SharedDtor(MessageLite& self) {
  JointDrill2SettleReq& this_ = static_cast<JointDrill2SettleReq&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  delete this_._impl_.sample_;
  delete this_._impl_.events_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL JointDrill2SettleReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) JointDrill2SettleReq(arena);
}
constexpr auto JointDrill2SettleReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(JointDrill2SettleReq),
                                            alignof(JointDrill2SettleReq));
}
constexpr auto JointDrill2SettleReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_JointDrill2SettleReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &JointDrill2SettleReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<JointDrill2SettleReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &JointDrill2SettleReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<JointDrill2SettleReq>(), &JointDrill2SettleReq::ByteSizeLong,
              &JointDrill2SettleReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_._cached_size_),
          false,
      },
      &JointDrill2SettleReq::kDescriptorMethods,
      &descriptor_table_joint_5fdrill_5f2_5fsettle_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull JointDrill2SettleReq_class_data_ =
        JointDrill2SettleReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
JointDrill2SettleReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&JointDrill2SettleReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(JointDrill2SettleReq_class_data_.tc_table);
  return JointDrill2SettleReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 0, 7>
JointDrill2SettleReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_._has_bits_),
    0, // no _extensions_
    2047, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967216,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    JointDrill2SettleReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::JointDrill2SettleReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 Time = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JointDrill2SettleReq, _impl_.time_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.time_)}},
    // uint32 Damage = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JointDrill2SettleReq, _impl_.damage_), 4>(),
     {16, 4, 0,
      PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.damage_)}},
    // .proto.TravelerDuelBattleSamples Sample = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.sample_)}},
    // uint64 Checksum = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(JointDrill2SettleReq, _impl_.checksum_), 5>(),
     {32, 5, 0,
      PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.checksum_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // .proto.Events Events = 7;
    {::_pbi::TcParser::FastMtS1,
     {58, 2, 1,
      PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.events_)}},
  }}, {{
    2047, 0, 1,
    65534, 5,
    65535, 65535
  }}, {{
    // uint32 Time = 1;
    {PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.time_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 Damage = 2;
    {PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.damage_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // .proto.TravelerDuelBattleSamples Sample = 3;
    {PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.sample_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint64 Checksum = 4;
    {PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.checksum_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // .proto.Events Events = 7;
    {PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.events_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.nextpackage_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::TravelerDuelBattleSamples>()},
      {::_pbi::TcParser::GetTable<::proto::Events>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void JointDrill2SettleReq::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.JointDrill2SettleReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.nextpackage_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.sample_ != nullptr);
      _impl_.sample_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.events_ != nullptr);
      _impl_.events_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000038U)) {
    ::memset(&_impl_.time_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.checksum_) -
        reinterpret_cast<char*>(&_impl_.time_)) + sizeof(_impl_.checksum_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL JointDrill2SettleReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const JointDrill2SettleReq& this_ = static_cast<const JointDrill2SettleReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL JointDrill2SettleReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const JointDrill2SettleReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.JointDrill2SettleReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 Time = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_time() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_time(), target);
    }
  }

  // uint32 Damage = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_damage() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_damage(), target);
    }
  }

  // .proto.TravelerDuelBattleSamples Sample = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.sample_, this_._impl_.sample_->GetCachedSize(), target,
        stream);
  }

  // uint64 Checksum = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_checksum() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_checksum(), target);
    }
  }

  // .proto.Events Events = 7;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        7, *this_._impl_.events_, this_._impl_.events_->GetCachedSize(), target,
        stream);
  }

  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.JointDrill2SettleReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t JointDrill2SettleReq::ByteSizeLong(const MessageLite& base) {
  const JointDrill2SettleReq& this_ = static_cast<const JointDrill2SettleReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t JointDrill2SettleReq::ByteSizeLong() const {
  const JointDrill2SettleReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.JointDrill2SettleReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
    // .proto.TravelerDuelBattleSamples Sample = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.sample_);
    }
    // .proto.Events Events = 7;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.events_);
    }
    // uint32 Time = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_time() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_time());
      }
    }
    // uint32 Damage = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_damage() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_damage());
      }
    }
    // uint64 Checksum = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_checksum() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_checksum());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void JointDrill2SettleReq::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<JointDrill2SettleReq*>(&to_msg);
  auto& from = static_cast<const JointDrill2SettleReq&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.JointDrill2SettleReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.sample_ != nullptr);
      if (_this->_impl_.sample_ == nullptr) {
        _this->_impl_.sample_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.sample_);
      } else {
        _this->_impl_.sample_->MergeFrom(*from._impl_.sample_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.events_ != nullptr);
      if (_this->_impl_.events_ == nullptr) {
        _this->_impl_.events_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.events_);
      } else {
        _this->_impl_.events_->MergeFrom(*from._impl_.events_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_time() != 0) {
        _this->_impl_.time_ = from._impl_.time_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_damage() != 0) {
        _this->_impl_.damage_ = from._impl_.damage_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_checksum() != 0) {
        _this->_impl_.checksum_ = from._impl_.checksum_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void JointDrill2SettleReq::CopyFrom(const JointDrill2SettleReq& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.JointDrill2SettleReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JointDrill2SettleReq::InternalSwap(JointDrill2SettleReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.checksum_)
      + sizeof(JointDrill2SettleReq::_impl_.checksum_)
      - PROTOBUF_FIELD_OFFSET(JointDrill2SettleReq, _impl_.sample_)>(
          reinterpret_cast<char*>(&_impl_.sample_),
          reinterpret_cast<char*>(&other->_impl_.sample_));
}

::google::protobuf::Metadata JointDrill2SettleReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_joint_5fdrill_5f2_5fsettle_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
