// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: player_honor_edit.proto
// Protobuf C++ Version: 6.33.4

#ifndef player_5fhonor_5fedit_2eproto_2epb_2eh
#define player_5fhonor_5fedit_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "public.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_player_5fhonor_5fedit_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_player_5fhonor_5fedit_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_player_5fhonor_5fedit_2eproto;
}  // extern "C"
namespace proto {
class PlayerHonorEditReq;
struct PlayerHonorEditReqDefaultTypeInternal;
extern PlayerHonorEditReqDefaultTypeInternal _PlayerHonorEditReq_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlayerHonorEditReq_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class PlayerHonorEditReq final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.PlayerHonorEditReq) */ {
 public:
  inline PlayerHonorEditReq() : PlayerHonorEditReq(nullptr) {}
  ~PlayerHonorEditReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlayerHonorEditReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlayerHonorEditReq));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlayerHonorEditReq(::google::protobuf::internal::ConstantInitialized);

  inline PlayerHonorEditReq(const PlayerHonorEditReq& from) : PlayerHonorEditReq(nullptr, from) {}
  inline PlayerHonorEditReq(PlayerHonorEditReq&& from) noexcept
      : PlayerHonorEditReq(nullptr, ::std::move(from)) {}
  inline PlayerHonorEditReq& operator=(const PlayerHonorEditReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerHonorEditReq& operator=(PlayerHonorEditReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerHonorEditReq& default_instance() {
    return *reinterpret_cast<const PlayerHonorEditReq*>(
        &_PlayerHonorEditReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PlayerHonorEditReq& a, PlayerHonorEditReq& b) { a.Swap(&b); }
  inline void Swap(PlayerHonorEditReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerHonorEditReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerHonorEditReq* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlayerHonorEditReq>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlayerHonorEditReq& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlayerHonorEditReq& from) { PlayerHonorEditReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlayerHonorEditReq* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.PlayerHonorEditReq"; }

  explicit PlayerHonorEditReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlayerHonorEditReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlayerHonorEditReq& from);
  PlayerHonorEditReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlayerHonorEditReq&& from) noexcept
      : PlayerHonorEditReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kListFieldNumber = 1,
    kNextPackageFieldNumber = 2047,
  };
  // repeated uint32 List = 1;
  int list_size() const;
  private:
  int _internal_list_size() const;

  public:
  void clear_list() ;
  ::uint32_t list(int index) const;
  void set_list(int index, ::uint32_t value);
  void add_list(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& list() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_list();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_list() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_list();

  public:
  // bytes NextPackage = 2047;
  void clear_nextpackage() ;
  const ::std::string& nextpackage() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_nextpackage(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_nextpackage();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_nextpackage();
  void set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_nextpackage() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_nextpackage(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_nextpackage();

  public:
  // @@protoc_insertion_point(class_scope:proto.PlayerHonorEditReq)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 2,
                                   0, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlayerHonorEditReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> list_;
    ::google::protobuf::internal::CachedSize _list_cached_byte_size_;
    ::google::protobuf::internal::ArenaStringPtr nextpackage_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_player_5fhonor_5fedit_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlayerHonorEditReq_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PlayerHonorEditReq

// repeated uint32 List = 1;
inline int PlayerHonorEditReq::_internal_list_size() const {
  return _internal_list().size();
}
inline int PlayerHonorEditReq::list_size() const {
  return _internal_list_size();
}
inline void PlayerHonorEditReq::clear_list() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.list_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t PlayerHonorEditReq::list(int index) const {
  // @@protoc_insertion_point(field_get:proto.PlayerHonorEditReq.List)
  return _internal_list().Get(index);
}
inline void PlayerHonorEditReq::set_list(int index, ::uint32_t value) {
  _internal_mutable_list()->Set(index, value);
  // @@protoc_insertion_point(field_set:proto.PlayerHonorEditReq.List)
}
inline void PlayerHonorEditReq::add_list(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_list()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:proto.PlayerHonorEditReq.List)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& PlayerHonorEditReq::list() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.PlayerHonorEditReq.List)
  return _internal_list();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL PlayerHonorEditReq::mutable_list()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:proto.PlayerHonorEditReq.List)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_list();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
PlayerHonorEditReq::_internal_list() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.list_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
PlayerHonorEditReq::_internal_mutable_list() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.list_;
}

// bytes NextPackage = 2047;
inline void PlayerHonorEditReq::clear_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& PlayerHonorEditReq::nextpackage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.PlayerHonorEditReq.NextPackage)
  return _internal_nextpackage();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void PlayerHonorEditReq::set_nextpackage(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.nextpackage_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.PlayerHonorEditReq.NextPackage)
}
inline ::std::string* PROTOBUF_NONNULL PlayerHonorEditReq::mutable_nextpackage()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_nextpackage();
  // @@protoc_insertion_point(field_mutable:proto.PlayerHonorEditReq.NextPackage)
  return _s;
}
inline const ::std::string& PlayerHonorEditReq::_internal_nextpackage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nextpackage_.Get();
}
inline void PlayerHonorEditReq::_internal_set_nextpackage(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nextpackage_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL PlayerHonorEditReq::_internal_mutable_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.nextpackage_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE PlayerHonorEditReq::release_nextpackage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.PlayerHonorEditReq.NextPackage)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.nextpackage_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  return released;
}
inline void PlayerHonorEditReq::set_allocated_nextpackage(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.nextpackage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.nextpackage_.IsDefault()) {
    _impl_.nextpackage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.PlayerHonorEditReq.NextPackage)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // player_5fhonor_5fedit_2eproto_2epb_2eh
