// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: resident_shop_purchase.proto
// Protobuf C++ Version: 6.33.4

#include "resident_shop_purchase.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr ResidentShopPurchaseReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        refreshtime_{::int64_t{0}},
        shopid_{0u},
        goodsid_{0u},
        number_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR ResidentShopPurchaseReq::ResidentShopPurchaseReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ResidentShopPurchaseReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResidentShopPurchaseReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResidentShopPurchaseReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResidentShopPurchaseReqDefaultTypeInternal() {}
  union {
    ResidentShopPurchaseReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResidentShopPurchaseReqDefaultTypeInternal _ResidentShopPurchaseReq_default_instance_;

inline constexpr ResidentShopPurchaseResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        shop_{nullptr},
        change_{nullptr},
        isrefresh_{false},
        purchasednumber_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR ResidentShopPurchaseResp::ResidentShopPurchaseResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ResidentShopPurchaseResp_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResidentShopPurchaseRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResidentShopPurchaseRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResidentShopPurchaseRespDefaultTypeInternal() {}
  union {
    ResidentShopPurchaseResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResidentShopPurchaseRespDefaultTypeInternal _ResidentShopPurchaseResp_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_resident_5fshop_5fpurchase_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_resident_5fshop_5fpurchase_2eproto = nullptr;
const ::uint32_t
    TableStruct_resident_5fshop_5fpurchase_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseReq, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseReq, _impl_.shopid_),
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseReq, _impl_.refreshtime_),
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseReq, _impl_.goodsid_),
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseReq, _impl_.number_),
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseReq, _impl_.nextpackage_),
        2,
        1,
        3,
        4,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseResp, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseResp, _impl_.isrefresh_),
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseResp, _impl_.shop_),
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseResp, _impl_.purchasednumber_),
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseResp, _impl_.change_),
        PROTOBUF_FIELD_OFFSET(::proto::ResidentShopPurchaseResp, _impl_.nextpackage_),
        3,
        1,
        4,
        2,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::ResidentShopPurchaseReq)},
        {13, sizeof(::proto::ResidentShopPurchaseResp)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_ResidentShopPurchaseReq_default_instance_._instance,
    &::proto::_ResidentShopPurchaseResp_default_instance_._instance,
};
const char descriptor_table_protodef_resident_5fshop_5fpurchase_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034resident_shop_purchase.proto\022\005proto\032\014p"
    "ublic.proto\"u\n\027ResidentShopPurchaseReq\022\016"
    "\n\006ShopId\030\001 \001(\r\022\023\n\013RefreshTime\030\002 \001(\003\022\017\n\007G"
    "oodsId\030\003 \001(\r\022\016\n\006Number\030\004 \001(\r\022\024\n\013NextPack"
    "age\030\377\017 \001(\014\"\242\001\n\030ResidentShopPurchaseResp\022"
    "\021\n\tIsRefresh\030\001 \001(\010\022!\n\004Shop\030\002 \001(\0132\023.proto"
    ".ResidentShop\022\027\n\017PurchasedNumber\030\003 \001(\r\022!"
    "\n\006Change\030\004 \001(\0132\021.proto.ChangeInfo\022\024\n\013Nex"
    "tPackage\030\377\017 \001(\014b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_resident_5fshop_5fpurchase_2eproto_deps[1] = {
        &::descriptor_table_public_2eproto,
};
static ::absl::once_flag descriptor_table_resident_5fshop_5fpurchase_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_resident_5fshop_5fpurchase_2eproto = {
    false,
    false,
    343,
    descriptor_table_protodef_resident_5fshop_5fpurchase_2eproto,
    "resident_shop_purchase.proto",
    &descriptor_table_resident_5fshop_5fpurchase_2eproto_once,
    descriptor_table_resident_5fshop_5fpurchase_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_resident_5fshop_5fpurchase_2eproto::offsets,
    file_level_enum_descriptors_resident_5fshop_5fpurchase_2eproto,
    file_level_service_descriptors_resident_5fshop_5fpurchase_2eproto,
};
namespace proto {
// ===================================================================

class ResidentShopPurchaseReq::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ResidentShopPurchaseReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_._has_bits_);
};

ResidentShopPurchaseReq::ResidentShopPurchaseReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResidentShopPurchaseReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.ResidentShopPurchaseReq)
}
PROTOBUF_NDEBUG_INLINE ResidentShopPurchaseReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::ResidentShopPurchaseReq& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nextpackage_(arena, from.nextpackage_) {}

ResidentShopPurchaseReq::ResidentShopPurchaseReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ResidentShopPurchaseReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResidentShopPurchaseReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResidentShopPurchaseReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, refreshtime_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, refreshtime_),
           offsetof(Impl_, number_) -
               offsetof(Impl_, refreshtime_) +
               sizeof(Impl_::number_));

  // @@protoc_insertion_point(copy_constructor:proto.ResidentShopPurchaseReq)
}
PROTOBUF_NDEBUG_INLINE ResidentShopPurchaseReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nextpackage_(arena) {}

inline void ResidentShopPurchaseReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, refreshtime_),
           0,
           offsetof(Impl_, number_) -
               offsetof(Impl_, refreshtime_) +
               sizeof(Impl_::number_));
}
ResidentShopPurchaseReq::~ResidentShopPurchaseReq() {
  // @@protoc_insertion_point(destructor:proto.ResidentShopPurchaseReq)
  SharedDtor(*this);
}
inline void ResidentShopPurchaseReq::SharedDtor(MessageLite& self) {
  ResidentShopPurchaseReq& this_ = static_cast<ResidentShopPurchaseReq&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ResidentShopPurchaseReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ResidentShopPurchaseReq(arena);
}
constexpr auto ResidentShopPurchaseReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResidentShopPurchaseReq),
                                            alignof(ResidentShopPurchaseReq));
}
constexpr auto ResidentShopPurchaseReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ResidentShopPurchaseReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ResidentShopPurchaseReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ResidentShopPurchaseReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ResidentShopPurchaseReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ResidentShopPurchaseReq>(), &ResidentShopPurchaseReq::ByteSizeLong,
              &ResidentShopPurchaseReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_._cached_size_),
          false,
      },
      &ResidentShopPurchaseReq::kDescriptorMethods,
      &descriptor_table_resident_5fshop_5fpurchase_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ResidentShopPurchaseReq_class_data_ =
        ResidentShopPurchaseReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ResidentShopPurchaseReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ResidentShopPurchaseReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ResidentShopPurchaseReq_class_data_.tc_table);
  return ResidentShopPurchaseReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 7>
ResidentShopPurchaseReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_._has_bits_),
    0, // no _extensions_
    2047, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ResidentShopPurchaseReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::ResidentShopPurchaseReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 ShopId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResidentShopPurchaseReq, _impl_.shopid_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.shopid_)}},
    // int64 RefreshTime = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ResidentShopPurchaseReq, _impl_.refreshtime_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.refreshtime_)}},
    // uint32 GoodsId = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResidentShopPurchaseReq, _impl_.goodsid_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.goodsid_)}},
    // uint32 Number = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResidentShopPurchaseReq, _impl_.number_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.number_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes NextPackage = 2047;
    {::_pbi::TcParser::FastBS2,
     {32762, 0, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.nextpackage_)}},
  }}, {{
    2047, 0, 1,
    65534, 4,
    65535, 65535
  }}, {{
    // uint32 ShopId = 1;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.shopid_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // int64 RefreshTime = 2;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.refreshtime_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // uint32 GoodsId = 3;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.goodsid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 Number = 4;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.number_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.nextpackage_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ResidentShopPurchaseReq::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ResidentShopPurchaseReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.nextpackage_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&_impl_.refreshtime_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.number_) -
        reinterpret_cast<char*>(&_impl_.refreshtime_)) + sizeof(_impl_.number_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ResidentShopPurchaseReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ResidentShopPurchaseReq& this_ = static_cast<const ResidentShopPurchaseReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ResidentShopPurchaseReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ResidentShopPurchaseReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.ResidentShopPurchaseReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 ShopId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_shopid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_shopid(), target);
    }
  }

  // int64 RefreshTime = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_refreshtime() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_refreshtime(), target);
    }
  }

  // uint32 GoodsId = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_goodsid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_goodsid(), target);
    }
  }

  // uint32 Number = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_number() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          4, this_._internal_number(), target);
    }
  }

  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.ResidentShopPurchaseReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ResidentShopPurchaseReq::ByteSizeLong(const MessageLite& base) {
  const ResidentShopPurchaseReq& this_ = static_cast<const ResidentShopPurchaseReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ResidentShopPurchaseReq::ByteSizeLong() const {
  const ResidentShopPurchaseReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.ResidentShopPurchaseReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
    // int64 RefreshTime = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_refreshtime() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_refreshtime());
      }
    }
    // uint32 ShopId = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_shopid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_shopid());
      }
    }
    // uint32 GoodsId = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_goodsid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_goodsid());
      }
    }
    // uint32 Number = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_number() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_number());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ResidentShopPurchaseReq::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ResidentShopPurchaseReq*>(&to_msg);
  auto& from = static_cast<const ResidentShopPurchaseReq&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.ResidentShopPurchaseReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_refreshtime() != 0) {
        _this->_impl_.refreshtime_ = from._impl_.refreshtime_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_shopid() != 0) {
        _this->_impl_.shopid_ = from._impl_.shopid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_goodsid() != 0) {
        _this->_impl_.goodsid_ = from._impl_.goodsid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_number() != 0) {
        _this->_impl_.number_ = from._impl_.number_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ResidentShopPurchaseReq::CopyFrom(const ResidentShopPurchaseReq& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.ResidentShopPurchaseReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResidentShopPurchaseReq::InternalSwap(ResidentShopPurchaseReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.number_)
      + sizeof(ResidentShopPurchaseReq::_impl_.number_)
      - PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseReq, _impl_.refreshtime_)>(
          reinterpret_cast<char*>(&_impl_.refreshtime_),
          reinterpret_cast<char*>(&other->_impl_.refreshtime_));
}

::google::protobuf::Metadata ResidentShopPurchaseReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResidentShopPurchaseResp::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ResidentShopPurchaseResp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_._has_bits_);
};

void ResidentShopPurchaseResp::clear_shop() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.shop_ != nullptr) _impl_.shop_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void ResidentShopPurchaseResp::clear_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.change_ != nullptr) _impl_.change_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
ResidentShopPurchaseResp::ResidentShopPurchaseResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResidentShopPurchaseResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.ResidentShopPurchaseResp)
}
PROTOBUF_NDEBUG_INLINE ResidentShopPurchaseResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::ResidentShopPurchaseResp& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nextpackage_(arena, from.nextpackage_) {}

ResidentShopPurchaseResp::ResidentShopPurchaseResp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ResidentShopPurchaseResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ResidentShopPurchaseResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResidentShopPurchaseResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.shop_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.shop_)
                : nullptr;
  _impl_.change_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, isrefresh_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, isrefresh_),
           offsetof(Impl_, purchasednumber_) -
               offsetof(Impl_, isrefresh_) +
               sizeof(Impl_::purchasednumber_));

  // @@protoc_insertion_point(copy_constructor:proto.ResidentShopPurchaseResp)
}
PROTOBUF_NDEBUG_INLINE ResidentShopPurchaseResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nextpackage_(arena) {}

inline void ResidentShopPurchaseResp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, shop_),
           0,
           offsetof(Impl_, purchasednumber_) -
               offsetof(Impl_, shop_) +
               sizeof(Impl_::purchasednumber_));
}
ResidentShopPurchaseResp::~ResidentShopPurchaseResp() {
  // @@protoc_insertion_point(destructor:proto.ResidentShopPurchaseResp)
  SharedDtor(*this);
}
inline void ResidentShopPurchaseResp::SharedDtor(MessageLite& self) {
  ResidentShopPurchaseResp& this_ = static_cast<ResidentShopPurchaseResp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  delete this_._impl_.shop_;
  delete this_._impl_.change_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ResidentShopPurchaseResp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ResidentShopPurchaseResp(arena);
}
constexpr auto ResidentShopPurchaseResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResidentShopPurchaseResp),
                                            alignof(ResidentShopPurchaseResp));
}
constexpr auto ResidentShopPurchaseResp::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ResidentShopPurchaseResp_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ResidentShopPurchaseResp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ResidentShopPurchaseResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ResidentShopPurchaseResp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ResidentShopPurchaseResp>(), &ResidentShopPurchaseResp::ByteSizeLong,
              &ResidentShopPurchaseResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_._cached_size_),
          false,
      },
      &ResidentShopPurchaseResp::kDescriptorMethods,
      &descriptor_table_resident_5fshop_5fpurchase_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ResidentShopPurchaseResp_class_data_ =
        ResidentShopPurchaseResp::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ResidentShopPurchaseResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ResidentShopPurchaseResp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ResidentShopPurchaseResp_class_data_.tc_table);
  return ResidentShopPurchaseResp_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 0, 7>
ResidentShopPurchaseResp::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_._has_bits_),
    0, // no _extensions_
    2047, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ResidentShopPurchaseResp_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::ResidentShopPurchaseResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool IsRefresh = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ResidentShopPurchaseResp, _impl_.isrefresh_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.isrefresh_)}},
    // .proto.ResidentShop Shop = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.shop_)}},
    // uint32 PurchasedNumber = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResidentShopPurchaseResp, _impl_.purchasednumber_), 4>(),
     {24, 4, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.purchasednumber_)}},
    // .proto.ChangeInfo Change = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 2, 1,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.change_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes NextPackage = 2047;
    {::_pbi::TcParser::FastBS2,
     {32762, 0, 0,
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.nextpackage_)}},
  }}, {{
    2047, 0, 1,
    65534, 4,
    65535, 65535
  }}, {{
    // bool IsRefresh = 1;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.isrefresh_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // .proto.ResidentShop Shop = 2;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.shop_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 PurchasedNumber = 3;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.purchasednumber_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // .proto.ChangeInfo Change = 4;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.change_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.nextpackage_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::ResidentShop>()},
      {::_pbi::TcParser::GetTable<::proto::ChangeInfo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ResidentShopPurchaseResp::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.ResidentShopPurchaseResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.nextpackage_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.shop_ != nullptr);
      _impl_.shop_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.change_ != nullptr);
      _impl_.change_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    ::memset(&_impl_.isrefresh_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.purchasednumber_) -
        reinterpret_cast<char*>(&_impl_.isrefresh_)) + sizeof(_impl_.purchasednumber_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ResidentShopPurchaseResp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ResidentShopPurchaseResp& this_ = static_cast<const ResidentShopPurchaseResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ResidentShopPurchaseResp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ResidentShopPurchaseResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.ResidentShopPurchaseResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool IsRefresh = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_isrefresh() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_isrefresh(), target);
    }
  }

  // .proto.ResidentShop Shop = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.shop_, this_._impl_.shop_->GetCachedSize(), target,
        stream);
  }

  // uint32 PurchasedNumber = 3;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_purchasednumber() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_purchasednumber(), target);
    }
  }

  // .proto.ChangeInfo Change = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.change_, this_._impl_.change_->GetCachedSize(), target,
        stream);
  }

  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.ResidentShopPurchaseResp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ResidentShopPurchaseResp::ByteSizeLong(const MessageLite& base) {
  const ResidentShopPurchaseResp& this_ = static_cast<const ResidentShopPurchaseResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ResidentShopPurchaseResp::ByteSizeLong() const {
  const ResidentShopPurchaseResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.ResidentShopPurchaseResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
    // .proto.ResidentShop Shop = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.shop_);
    }
    // .proto.ChangeInfo Change = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.change_);
    }
    // bool IsRefresh = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_isrefresh() != 0) {
        total_size += 2;
      }
    }
    // uint32 PurchasedNumber = 3;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_purchasednumber() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_purchasednumber());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ResidentShopPurchaseResp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ResidentShopPurchaseResp*>(&to_msg);
  auto& from = static_cast<const ResidentShopPurchaseResp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.ResidentShopPurchaseResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.shop_ != nullptr);
      if (_this->_impl_.shop_ == nullptr) {
        _this->_impl_.shop_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.shop_);
      } else {
        _this->_impl_.shop_->MergeFrom(*from._impl_.shop_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.change_ != nullptr);
      if (_this->_impl_.change_ == nullptr) {
        _this->_impl_.change_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_);
      } else {
        _this->_impl_.change_->MergeFrom(*from._impl_.change_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_isrefresh() != 0) {
        _this->_impl_.isrefresh_ = from._impl_.isrefresh_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_purchasednumber() != 0) {
        _this->_impl_.purchasednumber_ = from._impl_.purchasednumber_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ResidentShopPurchaseResp::CopyFrom(const ResidentShopPurchaseResp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.ResidentShopPurchaseResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResidentShopPurchaseResp::InternalSwap(ResidentShopPurchaseResp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.purchasednumber_)
      + sizeof(ResidentShopPurchaseResp::_impl_.purchasednumber_)
      - PROTOBUF_FIELD_OFFSET(ResidentShopPurchaseResp, _impl_.shop_)>(
          reinterpret_cast<char*>(&_impl_.shop_),
          reinterpret_cast<char*>(&other->_impl_.shop_));
}

::google::protobuf::Metadata ResidentShopPurchaseResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_resident_5fshop_5fpurchase_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
