// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: soldier_interact.proto
// Protobuf C++ Version: 6.33.4

#include "soldier_interact.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr SoldierInteractResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cases_{},
        effects_{},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        change_{nullptr},
        node_{nullptr},
        syncdata_{nullptr},
        id_{0u},
        Action_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR SoldierInteractResp::SoldierInteractResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SoldierInteractResp_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SoldierInteractRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SoldierInteractRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SoldierInteractRespDefaultTypeInternal() {}
  union {
    SoldierInteractResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SoldierInteractRespDefaultTypeInternal _SoldierInteractResp_default_instance_;

inline constexpr SoldierInteractReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nextpackage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0u},
        Action_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR SoldierInteractReq::SoldierInteractReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SoldierInteractReq_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SoldierInteractReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SoldierInteractReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SoldierInteractReqDefaultTypeInternal() {}
  union {
    SoldierInteractReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SoldierInteractReqDefaultTypeInternal _SoldierInteractReq_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_soldier_5finteract_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_soldier_5finteract_2eproto = nullptr;
const ::uint32_t
    TableStruct_soldier_5finteract_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_._oneof_case_[0]),
        15, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.nextpackage_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_.Action_),
        1,
        0,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_._oneof_case_[0]),
        19, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.cases_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.change_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.node_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.syncdata_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.effects_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.nextpackage_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.Action_),
        PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_.Action_),
        6,
        0,
        3,
        4,
        5,
        1,
        2,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::SoldierInteractReq)},
        {25, sizeof(::proto::SoldierInteractResp)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_SoldierInteractReq_default_instance_._instance,
    &::proto::_SoldierInteractResp_default_instance_._instance,
};
const char descriptor_table_protodef_soldier_5finteract_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026soldier_interact.proto\022\005proto\032\014public."
    "proto\032\024public_soldier.proto\"\246\004\n\022SoldierI"
    "nteractReq\022\n\n\002Id\030\001 \001(\r\022\024\n\013NextPackage\030\377\017"
    " \001(\014\022)\n\007ShopReq\030\002 \001(\0132\026.proto.InteractSh"
    "opReqH\000\022+\n\010FightReq\030\003 \001(\0132\027.proto.Intera"
    "ctFightReqH\000\0224\n\tBattleReq\030\004 \001(\0132\037.proto."
    "InteractSoldierBattleReqH\000\0224\n\tSelectReq\030"
    "\005 \001(\0132\037.proto.InteractSoldierSelectReqH\000"
    "\022Q\n\033EventSettlementOfDisputeReq\030\006 \001(\0132*."
    "proto.InteractEventSettlementOfDisputeRe"
    "qH\000\022]\n!EventSettlementOfDisputeBattleReq"
    "\030\007 \001(\01320.proto.InteractEventSettlementOf"
    "DisputeBattleReqH\000\0225\n\rDeploySyncReq\030\016 \001("
    "\0132\034.proto.InteractDeploySyncReqH\000\0227\n\016Cli"
    "entEventReq\030\017 \001(\0132\035.proto.InteractClient"
    "EventReqH\000B\010\n\006Action\"\240\005\n\023SoldierInteract"
    "Resp\022\n\n\002Id\030\001 \001(\r\022!\n\005Cases\030\002 \003(\0132\022.proto."
    "SoldierCase\022!\n\006Change\030\003 \001(\0132\021.proto.Chan"
    "geInfo\022$\n\004Node\030\004 \001(\0132\026.proto.SoldierNode"
    "Data\022(\n\010SyncData\030\005 \001(\0132\026.proto.SoldierSy"
    "ncData\022%\n\007Effects\030\006 \003(\0132\024.proto.SoldierE"
    "ffect\022\024\n\013NextPackage\030\377\017 \001(\014\022+\n\010ShopResp\030"
    "\010 \001(\0132\027.proto.InteractShopRespH\000\0226\n\nBatt"
    "leResp\030\t \001(\0132 .proto.InteractSoldierBatt"
    "leRespH\000\0226\n\nSelectResp\030\n \001(\0132 .proto.Int"
    "eractSoldierSelectRespH\000\022S\n\034EventSettlem"
    "entOfDisputeResp\030\013 \001(\0132+.proto.InteractE"
    "ventSettlementOfDisputeRespH\000\022_\n\"EventSe"
    "ttlementOfDisputeBattleResp\030\014 \001(\01321.prot"
    "o.InteractEventSettlementOfDisputeBattle"
    "RespH\000\022\035\n\007NilResp\030\016 \001(\0132\n.proto.NilH\000\022.\n"
    "\006Settle\030\017 \001(\0132\034.proto.SoldierSettleDataR"
    "espH\000B\010\n\006Actionb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_soldier_5finteract_2eproto_deps[2] = {
        &::descriptor_table_public_2eproto,
        &::descriptor_table_public_5fsoldier_2eproto,
};
static ::absl::once_flag descriptor_table_soldier_5finteract_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_soldier_5finteract_2eproto = {
    false,
    false,
    1303,
    descriptor_table_protodef_soldier_5finteract_2eproto,
    "soldier_interact.proto",
    &descriptor_table_soldier_5finteract_2eproto_once,
    descriptor_table_soldier_5finteract_2eproto_deps,
    2,
    2,
    schemas,
    file_default_instances,
    TableStruct_soldier_5finteract_2eproto::offsets,
    file_level_enum_descriptors_soldier_5finteract_2eproto,
    file_level_service_descriptors_soldier_5finteract_2eproto,
};
namespace proto {
// ===================================================================

class SoldierInteractReq::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SoldierInteractReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractReq, _impl_._oneof_case_);
};

void SoldierInteractReq::set_allocated_shopreq(::proto::InteractShopReq* PROTOBUF_NULLABLE shopreq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (shopreq) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(shopreq)->GetArena();
    if (message_arena != submessage_arena) {
      shopreq = ::google::protobuf::internal::GetOwnedMessage(message_arena, shopreq, submessage_arena);
    }
    set_has_shopreq();
    _impl_.Action_.shopreq_ = shopreq;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractReq.ShopReq)
}
void SoldierInteractReq::clear_shopreq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kShopReq) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.shopreq_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.shopreq_);
    }
    clear_has_Action();
  }
}
void SoldierInteractReq::set_allocated_fightreq(::proto::InteractFightReq* PROTOBUF_NULLABLE fightreq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (fightreq) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(fightreq)->GetArena();
    if (message_arena != submessage_arena) {
      fightreq = ::google::protobuf::internal::GetOwnedMessage(message_arena, fightreq, submessage_arena);
    }
    set_has_fightreq();
    _impl_.Action_.fightreq_ = fightreq;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractReq.FightReq)
}
void SoldierInteractReq::clear_fightreq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kFightReq) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.fightreq_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.fightreq_);
    }
    clear_has_Action();
  }
}
void SoldierInteractReq::set_allocated_battlereq(::proto::InteractSoldierBattleReq* PROTOBUF_NULLABLE battlereq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (battlereq) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(battlereq)->GetArena();
    if (message_arena != submessage_arena) {
      battlereq = ::google::protobuf::internal::GetOwnedMessage(message_arena, battlereq, submessage_arena);
    }
    set_has_battlereq();
    _impl_.Action_.battlereq_ = battlereq;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractReq.BattleReq)
}
void SoldierInteractReq::clear_battlereq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kBattleReq) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.battlereq_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.battlereq_);
    }
    clear_has_Action();
  }
}
void SoldierInteractReq::set_allocated_selectreq(::proto::InteractSoldierSelectReq* PROTOBUF_NULLABLE selectreq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (selectreq) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(selectreq)->GetArena();
    if (message_arena != submessage_arena) {
      selectreq = ::google::protobuf::internal::GetOwnedMessage(message_arena, selectreq, submessage_arena);
    }
    set_has_selectreq();
    _impl_.Action_.selectreq_ = selectreq;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractReq.SelectReq)
}
void SoldierInteractReq::clear_selectreq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kSelectReq) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.selectreq_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.selectreq_);
    }
    clear_has_Action();
  }
}
void SoldierInteractReq::set_allocated_eventsettlementofdisputereq(::proto::InteractEventSettlementOfDisputeReq* PROTOBUF_NULLABLE eventsettlementofdisputereq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (eventsettlementofdisputereq) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(eventsettlementofdisputereq)->GetArena();
    if (message_arena != submessage_arena) {
      eventsettlementofdisputereq = ::google::protobuf::internal::GetOwnedMessage(message_arena, eventsettlementofdisputereq, submessage_arena);
    }
    set_has_eventsettlementofdisputereq();
    _impl_.Action_.eventsettlementofdisputereq_ = eventsettlementofdisputereq;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractReq.EventSettlementOfDisputeReq)
}
void SoldierInteractReq::clear_eventsettlementofdisputereq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kEventSettlementOfDisputeReq) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.eventsettlementofdisputereq_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.eventsettlementofdisputereq_);
    }
    clear_has_Action();
  }
}
void SoldierInteractReq::set_allocated_eventsettlementofdisputebattlereq(::proto::InteractEventSettlementOfDisputeBattleReq* PROTOBUF_NULLABLE eventsettlementofdisputebattlereq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (eventsettlementofdisputebattlereq) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(eventsettlementofdisputebattlereq)->GetArena();
    if (message_arena != submessage_arena) {
      eventsettlementofdisputebattlereq = ::google::protobuf::internal::GetOwnedMessage(message_arena, eventsettlementofdisputebattlereq, submessage_arena);
    }
    set_has_eventsettlementofdisputebattlereq();
    _impl_.Action_.eventsettlementofdisputebattlereq_ = eventsettlementofdisputebattlereq;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractReq.EventSettlementOfDisputeBattleReq)
}
void SoldierInteractReq::clear_eventsettlementofdisputebattlereq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kEventSettlementOfDisputeBattleReq) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.eventsettlementofdisputebattlereq_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.eventsettlementofdisputebattlereq_);
    }
    clear_has_Action();
  }
}
void SoldierInteractReq::set_allocated_deploysyncreq(::proto::InteractDeploySyncReq* PROTOBUF_NULLABLE deploysyncreq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (deploysyncreq) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(deploysyncreq)->GetArena();
    if (message_arena != submessage_arena) {
      deploysyncreq = ::google::protobuf::internal::GetOwnedMessage(message_arena, deploysyncreq, submessage_arena);
    }
    set_has_deploysyncreq();
    _impl_.Action_.deploysyncreq_ = deploysyncreq;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractReq.DeploySyncReq)
}
void SoldierInteractReq::clear_deploysyncreq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kDeploySyncReq) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.deploysyncreq_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.deploysyncreq_);
    }
    clear_has_Action();
  }
}
void SoldierInteractReq::set_allocated_clienteventreq(::proto::InteractClientEventReq* PROTOBUF_NULLABLE clienteventreq) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (clienteventreq) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(clienteventreq)->GetArena();
    if (message_arena != submessage_arena) {
      clienteventreq = ::google::protobuf::internal::GetOwnedMessage(message_arena, clienteventreq, submessage_arena);
    }
    set_has_clienteventreq();
    _impl_.Action_.clienteventreq_ = clienteventreq;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractReq.ClientEventReq)
}
void SoldierInteractReq::clear_clienteventreq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kClientEventReq) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.clienteventreq_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.clienteventreq_);
    }
    clear_has_Action();
  }
}
SoldierInteractReq::SoldierInteractReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SoldierInteractReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SoldierInteractReq)
}
PROTOBUF_NDEBUG_INLINE SoldierInteractReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::SoldierInteractReq& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nextpackage_(arena, from.nextpackage_),
        Action_{},
        _oneof_case_{from._oneof_case_[0]} {}

SoldierInteractReq::SoldierInteractReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SoldierInteractReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SoldierInteractReq_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SoldierInteractReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;
  switch (Action_case()) {
    case ACTION_NOT_SET:
      break;
      case kShopReq:
        _impl_.Action_.shopreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.shopreq_);
        break;
      case kFightReq:
        _impl_.Action_.fightreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.fightreq_);
        break;
      case kBattleReq:
        _impl_.Action_.battlereq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.battlereq_);
        break;
      case kSelectReq:
        _impl_.Action_.selectreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.selectreq_);
        break;
      case kEventSettlementOfDisputeReq:
        _impl_.Action_.eventsettlementofdisputereq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.eventsettlementofdisputereq_);
        break;
      case kEventSettlementOfDisputeBattleReq:
        _impl_.Action_.eventsettlementofdisputebattlereq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.eventsettlementofdisputebattlereq_);
        break;
      case kDeploySyncReq:
        _impl_.Action_.deploysyncreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.deploysyncreq_);
        break;
      case kClientEventReq:
        _impl_.Action_.clienteventreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.clienteventreq_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:proto.SoldierInteractReq)
}
PROTOBUF_NDEBUG_INLINE SoldierInteractReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nextpackage_(arena),
        Action_{},
        _oneof_case_{} {}

inline void SoldierInteractReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
SoldierInteractReq::~SoldierInteractReq() {
  // @@protoc_insertion_point(destructor:proto.SoldierInteractReq)
  SharedDtor(*this);
}
inline void SoldierInteractReq::SharedDtor(MessageLite& self) {
  SoldierInteractReq& this_ = static_cast<SoldierInteractReq&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  if (this_.has_Action()) {
    this_.clear_Action();
  }
  this_._impl_.~Impl_();
}

void SoldierInteractReq::clear_Action() {
// @@protoc_insertion_point(one_of_clear_start:proto.SoldierInteractReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (Action_case()) {
    case kShopReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.shopreq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.shopreq_);
      }
      break;
    }
    case kFightReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.fightreq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.fightreq_);
      }
      break;
    }
    case kBattleReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.battlereq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.battlereq_);
      }
      break;
    }
    case kSelectReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.selectreq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.selectreq_);
      }
      break;
    }
    case kEventSettlementOfDisputeReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.eventsettlementofdisputereq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.eventsettlementofdisputereq_);
      }
      break;
    }
    case kEventSettlementOfDisputeBattleReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.eventsettlementofdisputebattlereq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.eventsettlementofdisputebattlereq_);
      }
      break;
    }
    case kDeploySyncReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.deploysyncreq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.deploysyncreq_);
      }
      break;
    }
    case kClientEventReq: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.clienteventreq_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.clienteventreq_);
      }
      break;
    }
    case ACTION_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ACTION_NOT_SET;
}


inline void* PROTOBUF_NONNULL SoldierInteractReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SoldierInteractReq(arena);
}
constexpr auto SoldierInteractReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SoldierInteractReq),
                                            alignof(SoldierInteractReq));
}
constexpr auto SoldierInteractReq::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SoldierInteractReq_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SoldierInteractReq::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SoldierInteractReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SoldierInteractReq::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SoldierInteractReq>(), &SoldierInteractReq::ByteSizeLong,
              &SoldierInteractReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_._cached_size_),
          false,
      },
      &SoldierInteractReq::kDescriptorMethods,
      &descriptor_table_soldier_5finteract_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SoldierInteractReq_class_data_ =
        SoldierInteractReq::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SoldierInteractReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SoldierInteractReq_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SoldierInteractReq_class_data_.tc_table);
  return SoldierInteractReq_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 10, 8, 0, 7>
SoldierInteractReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_._has_bits_),
    0, // no _extensions_
    2047, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294942592,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    8,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SoldierInteractReq_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SoldierInteractReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 Id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SoldierInteractReq, _impl_.id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.id_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes NextPackage = 2047;
    {::_pbi::TcParser::FastBS2,
     {32762, 0, 0,
      PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.nextpackage_)}},
  }}, {{
    2047, 0, 1,
    65534, 9,
    65535, 65535
  }}, {{
    // uint32 Id = 1;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // .proto.InteractShopReq ShopReq = 2;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.Action_.shopreq_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractFightReq FightReq = 3;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.Action_.fightreq_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractSoldierBattleReq BattleReq = 4;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.Action_.battlereq_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractSoldierSelectReq SelectReq = 5;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.Action_.selectreq_), _Internal::kOneofCaseOffset + 0, 3, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractEventSettlementOfDisputeReq EventSettlementOfDisputeReq = 6;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.Action_.eventsettlementofdisputereq_), _Internal::kOneofCaseOffset + 0, 4, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractEventSettlementOfDisputeBattleReq EventSettlementOfDisputeBattleReq = 7;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.Action_.eventsettlementofdisputebattlereq_), _Internal::kOneofCaseOffset + 0, 5, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractDeploySyncReq DeploySyncReq = 14;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.Action_.deploysyncreq_), _Internal::kOneofCaseOffset + 0, 6, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractClientEventReq ClientEventReq = 15;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.Action_.clienteventreq_), _Internal::kOneofCaseOffset + 0, 7, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractReq, _impl_.nextpackage_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::InteractShopReq>()},
      {::_pbi::TcParser::GetTable<::proto::InteractFightReq>()},
      {::_pbi::TcParser::GetTable<::proto::InteractSoldierBattleReq>()},
      {::_pbi::TcParser::GetTable<::proto::InteractSoldierSelectReq>()},
      {::_pbi::TcParser::GetTable<::proto::InteractEventSettlementOfDisputeReq>()},
      {::_pbi::TcParser::GetTable<::proto::InteractEventSettlementOfDisputeBattleReq>()},
      {::_pbi::TcParser::GetTable<::proto::InteractDeploySyncReq>()},
      {::_pbi::TcParser::GetTable<::proto::InteractClientEventReq>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SoldierInteractReq::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SoldierInteractReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.nextpackage_.ClearNonDefaultToEmpty();
  }
  _impl_.id_ = 0u;
  clear_Action();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SoldierInteractReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SoldierInteractReq& this_ = static_cast<const SoldierInteractReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SoldierInteractReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SoldierInteractReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.SoldierInteractReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 Id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_id(), target);
    }
  }

  switch (this_.Action_case()) {
    case kShopReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.Action_.shopreq_, this_._impl_.Action_.shopreq_->GetCachedSize(), target,
          stream);
      break;
    }
    case kFightReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.Action_.fightreq_, this_._impl_.Action_.fightreq_->GetCachedSize(), target,
          stream);
      break;
    }
    case kBattleReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.Action_.battlereq_, this_._impl_.Action_.battlereq_->GetCachedSize(), target,
          stream);
      break;
    }
    case kSelectReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *this_._impl_.Action_.selectreq_, this_._impl_.Action_.selectreq_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEventSettlementOfDisputeReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          6, *this_._impl_.Action_.eventsettlementofdisputereq_, this_._impl_.Action_.eventsettlementofdisputereq_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEventSettlementOfDisputeBattleReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          7, *this_._impl_.Action_.eventsettlementofdisputebattlereq_, this_._impl_.Action_.eventsettlementofdisputebattlereq_->GetCachedSize(), target,
          stream);
      break;
    }
    case kDeploySyncReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          14, *this_._impl_.Action_.deploysyncreq_, this_._impl_.Action_.deploysyncreq_->GetCachedSize(), target,
          stream);
      break;
    }
    case kClientEventReq: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          15, *this_._impl_.Action_.clienteventreq_, this_._impl_.Action_.clienteventreq_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SoldierInteractReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SoldierInteractReq::ByteSizeLong(const MessageLite& base) {
  const SoldierInteractReq& this_ = static_cast<const SoldierInteractReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SoldierInteractReq::ByteSizeLong() const {
  const SoldierInteractReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SoldierInteractReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
    // uint32 Id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_id());
      }
    }
  }
  switch (this_.Action_case()) {
    // .proto.InteractShopReq ShopReq = 2;
    case kShopReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.shopreq_);
      break;
    }
    // .proto.InteractFightReq FightReq = 3;
    case kFightReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.fightreq_);
      break;
    }
    // .proto.InteractSoldierBattleReq BattleReq = 4;
    case kBattleReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.battlereq_);
      break;
    }
    // .proto.InteractSoldierSelectReq SelectReq = 5;
    case kSelectReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.selectreq_);
      break;
    }
    // .proto.InteractEventSettlementOfDisputeReq EventSettlementOfDisputeReq = 6;
    case kEventSettlementOfDisputeReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.eventsettlementofdisputereq_);
      break;
    }
    // .proto.InteractEventSettlementOfDisputeBattleReq EventSettlementOfDisputeBattleReq = 7;
    case kEventSettlementOfDisputeBattleReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.eventsettlementofdisputebattlereq_);
      break;
    }
    // .proto.InteractDeploySyncReq DeploySyncReq = 14;
    case kDeploySyncReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.deploysyncreq_);
      break;
    }
    // .proto.InteractClientEventReq ClientEventReq = 15;
    case kClientEventReq: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.clienteventreq_);
      break;
    }
    case ACTION_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SoldierInteractReq::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SoldierInteractReq*>(&to_msg);
  auto& from = static_cast<const SoldierInteractReq&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SoldierInteractReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_Action();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kShopReq: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.shopreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.shopreq_);
        } else {
          _this->_impl_.Action_.shopreq_->MergeFrom(*from._impl_.Action_.shopreq_);
        }
        break;
      }
      case kFightReq: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.fightreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.fightreq_);
        } else {
          _this->_impl_.Action_.fightreq_->MergeFrom(*from._impl_.Action_.fightreq_);
        }
        break;
      }
      case kBattleReq: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.battlereq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.battlereq_);
        } else {
          _this->_impl_.Action_.battlereq_->MergeFrom(*from._impl_.Action_.battlereq_);
        }
        break;
      }
      case kSelectReq: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.selectreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.selectreq_);
        } else {
          _this->_impl_.Action_.selectreq_->MergeFrom(*from._impl_.Action_.selectreq_);
        }
        break;
      }
      case kEventSettlementOfDisputeReq: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.eventsettlementofdisputereq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.eventsettlementofdisputereq_);
        } else {
          _this->_impl_.Action_.eventsettlementofdisputereq_->MergeFrom(*from._impl_.Action_.eventsettlementofdisputereq_);
        }
        break;
      }
      case kEventSettlementOfDisputeBattleReq: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.eventsettlementofdisputebattlereq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.eventsettlementofdisputebattlereq_);
        } else {
          _this->_impl_.Action_.eventsettlementofdisputebattlereq_->MergeFrom(*from._impl_.Action_.eventsettlementofdisputebattlereq_);
        }
        break;
      }
      case kDeploySyncReq: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.deploysyncreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.deploysyncreq_);
        } else {
          _this->_impl_.Action_.deploysyncreq_->MergeFrom(*from._impl_.Action_.deploysyncreq_);
        }
        break;
      }
      case kClientEventReq: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.clienteventreq_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.clienteventreq_);
        } else {
          _this->_impl_.Action_.clienteventreq_->MergeFrom(*from._impl_.Action_.clienteventreq_);
        }
        break;
      }
      case ACTION_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SoldierInteractReq::CopyFrom(const SoldierInteractReq& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.SoldierInteractReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SoldierInteractReq::InternalSwap(SoldierInteractReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
  swap(_impl_.id_, other->_impl_.id_);
  swap(_impl_.Action_, other->_impl_.Action_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata SoldierInteractReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SoldierInteractResp::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SoldierInteractResp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::proto::SoldierInteractResp, _impl_._oneof_case_);
};

void SoldierInteractResp::clear_cases() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cases_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
void SoldierInteractResp::clear_change() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.change_ != nullptr) _impl_.change_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
void SoldierInteractResp::clear_node() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.node_ != nullptr) _impl_.node_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
void SoldierInteractResp::clear_syncdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.syncdata_ != nullptr) _impl_.syncdata_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
void SoldierInteractResp::clear_effects() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.effects_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
void SoldierInteractResp::set_allocated_shopresp(::proto::InteractShopResp* PROTOBUF_NULLABLE shopresp) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (shopresp) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(shopresp)->GetArena();
    if (message_arena != submessage_arena) {
      shopresp = ::google::protobuf::internal::GetOwnedMessage(message_arena, shopresp, submessage_arena);
    }
    set_has_shopresp();
    _impl_.Action_.shopresp_ = shopresp;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractResp.ShopResp)
}
void SoldierInteractResp::clear_shopresp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kShopResp) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.shopresp_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.shopresp_);
    }
    clear_has_Action();
  }
}
void SoldierInteractResp::set_allocated_battleresp(::proto::InteractSoldierBattleResp* PROTOBUF_NULLABLE battleresp) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (battleresp) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(battleresp)->GetArena();
    if (message_arena != submessage_arena) {
      battleresp = ::google::protobuf::internal::GetOwnedMessage(message_arena, battleresp, submessage_arena);
    }
    set_has_battleresp();
    _impl_.Action_.battleresp_ = battleresp;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractResp.BattleResp)
}
void SoldierInteractResp::clear_battleresp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kBattleResp) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.battleresp_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.battleresp_);
    }
    clear_has_Action();
  }
}
void SoldierInteractResp::set_allocated_selectresp(::proto::InteractSoldierSelectResp* PROTOBUF_NULLABLE selectresp) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (selectresp) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(selectresp)->GetArena();
    if (message_arena != submessage_arena) {
      selectresp = ::google::protobuf::internal::GetOwnedMessage(message_arena, selectresp, submessage_arena);
    }
    set_has_selectresp();
    _impl_.Action_.selectresp_ = selectresp;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractResp.SelectResp)
}
void SoldierInteractResp::clear_selectresp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kSelectResp) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.selectresp_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.selectresp_);
    }
    clear_has_Action();
  }
}
void SoldierInteractResp::set_allocated_eventsettlementofdisputeresp(::proto::InteractEventSettlementOfDisputeResp* PROTOBUF_NULLABLE eventsettlementofdisputeresp) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (eventsettlementofdisputeresp) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(eventsettlementofdisputeresp)->GetArena();
    if (message_arena != submessage_arena) {
      eventsettlementofdisputeresp = ::google::protobuf::internal::GetOwnedMessage(message_arena, eventsettlementofdisputeresp, submessage_arena);
    }
    set_has_eventsettlementofdisputeresp();
    _impl_.Action_.eventsettlementofdisputeresp_ = eventsettlementofdisputeresp;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractResp.EventSettlementOfDisputeResp)
}
void SoldierInteractResp::clear_eventsettlementofdisputeresp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kEventSettlementOfDisputeResp) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.eventsettlementofdisputeresp_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.eventsettlementofdisputeresp_);
    }
    clear_has_Action();
  }
}
void SoldierInteractResp::set_allocated_eventsettlementofdisputebattleresp(::proto::InteractEventSettlementOfDisputeBattleResp* PROTOBUF_NULLABLE eventsettlementofdisputebattleresp) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (eventsettlementofdisputebattleresp) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(eventsettlementofdisputebattleresp)->GetArena();
    if (message_arena != submessage_arena) {
      eventsettlementofdisputebattleresp = ::google::protobuf::internal::GetOwnedMessage(message_arena, eventsettlementofdisputebattleresp, submessage_arena);
    }
    set_has_eventsettlementofdisputebattleresp();
    _impl_.Action_.eventsettlementofdisputebattleresp_ = eventsettlementofdisputebattleresp;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractResp.EventSettlementOfDisputeBattleResp)
}
void SoldierInteractResp::clear_eventsettlementofdisputebattleresp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kEventSettlementOfDisputeBattleResp) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.eventsettlementofdisputebattleresp_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.eventsettlementofdisputebattleresp_);
    }
    clear_has_Action();
  }
}
void SoldierInteractResp::set_allocated_nilresp(::proto::Nil* PROTOBUF_NULLABLE nilresp) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (nilresp) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(nilresp)->GetArena();
    if (message_arena != submessage_arena) {
      nilresp = ::google::protobuf::internal::GetOwnedMessage(message_arena, nilresp, submessage_arena);
    }
    set_has_nilresp();
    _impl_.Action_.nilresp_ = nilresp;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractResp.NilResp)
}
void SoldierInteractResp::clear_nilresp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kNilResp) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.nilresp_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.nilresp_);
    }
    clear_has_Action();
  }
}
void SoldierInteractResp::set_allocated_settle(::proto::SoldierSettleDataResp* PROTOBUF_NULLABLE settle) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_Action();
  if (settle) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(settle)->GetArena();
    if (message_arena != submessage_arena) {
      settle = ::google::protobuf::internal::GetOwnedMessage(message_arena, settle, submessage_arena);
    }
    set_has_settle();
    _impl_.Action_.settle_ = settle;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SoldierInteractResp.Settle)
}
void SoldierInteractResp::clear_settle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (Action_case() == kSettle) {
    if (GetArena() == nullptr) {
      delete _impl_.Action_.settle_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.settle_);
    }
    clear_has_Action();
  }
}
SoldierInteractResp::SoldierInteractResp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SoldierInteractResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SoldierInteractResp)
}
PROTOBUF_NDEBUG_INLINE SoldierInteractResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::SoldierInteractResp& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        cases_{visibility, arena, from.cases_},
        effects_{visibility, arena, from.effects_},
        nextpackage_(arena, from.nextpackage_),
        Action_{},
        _oneof_case_{from._oneof_case_[0]} {}

SoldierInteractResp::SoldierInteractResp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SoldierInteractResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SoldierInteractResp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SoldierInteractResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.change_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_)
                : nullptr;
  _impl_.node_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.node_)
                : nullptr;
  _impl_.syncdata_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.syncdata_)
                : nullptr;
  _impl_.id_ = from._impl_.id_;
  switch (Action_case()) {
    case ACTION_NOT_SET:
      break;
      case kShopResp:
        _impl_.Action_.shopresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.shopresp_);
        break;
      case kBattleResp:
        _impl_.Action_.battleresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.battleresp_);
        break;
      case kSelectResp:
        _impl_.Action_.selectresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.selectresp_);
        break;
      case kEventSettlementOfDisputeResp:
        _impl_.Action_.eventsettlementofdisputeresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.eventsettlementofdisputeresp_);
        break;
      case kEventSettlementOfDisputeBattleResp:
        _impl_.Action_.eventsettlementofdisputebattleresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.eventsettlementofdisputebattleresp_);
        break;
      case kNilResp:
        _impl_.Action_.nilresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.nilresp_);
        break;
      case kSettle:
        _impl_.Action_.settle_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.settle_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:proto.SoldierInteractResp)
}
PROTOBUF_NDEBUG_INLINE SoldierInteractResp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        cases_{visibility, arena},
        effects_{visibility, arena},
        nextpackage_(arena),
        Action_{},
        _oneof_case_{} {}

inline void SoldierInteractResp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, change_),
           0,
           offsetof(Impl_, id_) -
               offsetof(Impl_, change_) +
               sizeof(Impl_::id_));
}
SoldierInteractResp::~SoldierInteractResp() {
  // @@protoc_insertion_point(destructor:proto.SoldierInteractResp)
  SharedDtor(*this);
}
inline void SoldierInteractResp::SharedDtor(MessageLite& self) {
  SoldierInteractResp& this_ = static_cast<SoldierInteractResp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nextpackage_.Destroy();
  delete this_._impl_.change_;
  delete this_._impl_.node_;
  delete this_._impl_.syncdata_;
  if (this_.has_Action()) {
    this_.clear_Action();
  }
  this_._impl_.~Impl_();
}

void SoldierInteractResp::clear_Action() {
// @@protoc_insertion_point(one_of_clear_start:proto.SoldierInteractResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (Action_case()) {
    case kShopResp: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.shopresp_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.shopresp_);
      }
      break;
    }
    case kBattleResp: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.battleresp_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.battleresp_);
      }
      break;
    }
    case kSelectResp: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.selectresp_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.selectresp_);
      }
      break;
    }
    case kEventSettlementOfDisputeResp: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.eventsettlementofdisputeresp_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.eventsettlementofdisputeresp_);
      }
      break;
    }
    case kEventSettlementOfDisputeBattleResp: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.eventsettlementofdisputebattleresp_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.eventsettlementofdisputebattleresp_);
      }
      break;
    }
    case kNilResp: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.nilresp_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.nilresp_);
      }
      break;
    }
    case kSettle: {
      if (GetArena() == nullptr) {
        delete _impl_.Action_.settle_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.Action_.settle_);
      }
      break;
    }
    case ACTION_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ACTION_NOT_SET;
}


inline void* PROTOBUF_NONNULL SoldierInteractResp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SoldierInteractResp(arena);
}
constexpr auto SoldierInteractResp::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.cases_) +
          decltype(SoldierInteractResp::_impl_.cases_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.effects_) +
          decltype(SoldierInteractResp::_impl_.effects_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(SoldierInteractResp), alignof(SoldierInteractResp), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SoldierInteractResp::PlacementNew_,
                                 sizeof(SoldierInteractResp),
                                 alignof(SoldierInteractResp));
  }
}
constexpr auto SoldierInteractResp::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SoldierInteractResp_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SoldierInteractResp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SoldierInteractResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SoldierInteractResp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SoldierInteractResp>(), &SoldierInteractResp::ByteSizeLong,
              &SoldierInteractResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_._cached_size_),
          false,
      },
      &SoldierInteractResp::kDescriptorMethods,
      &descriptor_table_soldier_5finteract_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SoldierInteractResp_class_data_ =
        SoldierInteractResp::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SoldierInteractResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SoldierInteractResp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SoldierInteractResp_class_data_.tc_table);
  return SoldierInteractResp_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 14, 12, 0, 7>
SoldierInteractResp::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_._has_bits_),
    0, // no _extensions_
    2047, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294938688,  // skipmap
    offsetof(decltype(_table_), field_entries),
    14,  // num_field_entries
    12,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SoldierInteractResp_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SoldierInteractResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 Id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SoldierInteractResp, _impl_.id_), 6>(),
     {8, 6, 0,
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.id_)}},
    // repeated .proto.SoldierCase Cases = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.cases_)}},
    // .proto.ChangeInfo Change = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 3, 1,
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.change_)}},
    // .proto.SoldierNodeData Node = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 4, 2,
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.node_)}},
    // .proto.SoldierSyncData SyncData = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 5, 3,
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.syncdata_)}},
    // repeated .proto.SoldierEffect Effects = 6;
    {::_pbi::TcParser::FastMtR1,
     {50, 1, 4,
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.effects_)}},
    // bytes NextPackage = 2047;
    {::_pbi::TcParser::FastBS2,
     {32762, 2, 0,
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.nextpackage_)}},
  }}, {{
    2047, 0, 1,
    65534, 13,
    65535, 65535
  }}, {{
    // uint32 Id = 1;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.id_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated .proto.SoldierCase Cases = 2;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.cases_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.ChangeInfo Change = 3;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.change_), _Internal::kHasBitsOffset + 3, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.SoldierNodeData Node = 4;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.node_), _Internal::kHasBitsOffset + 4, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.SoldierSyncData SyncData = 5;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.syncdata_), _Internal::kHasBitsOffset + 5, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .proto.SoldierEffect Effects = 6;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.effects_), _Internal::kHasBitsOffset + 1, 4, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractShopResp ShopResp = 8;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.Action_.shopresp_), _Internal::kOneofCaseOffset + 0, 5, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractSoldierBattleResp BattleResp = 9;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.Action_.battleresp_), _Internal::kOneofCaseOffset + 0, 6, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractSoldierSelectResp SelectResp = 10;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.Action_.selectresp_), _Internal::kOneofCaseOffset + 0, 7, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractEventSettlementOfDisputeResp EventSettlementOfDisputeResp = 11;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.Action_.eventsettlementofdisputeresp_), _Internal::kOneofCaseOffset + 0, 8, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.InteractEventSettlementOfDisputeBattleResp EventSettlementOfDisputeBattleResp = 12;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.Action_.eventsettlementofdisputebattleresp_), _Internal::kOneofCaseOffset + 0, 9, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.Nil NilResp = 14;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.Action_.nilresp_), _Internal::kOneofCaseOffset + 0, 10, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .proto.SoldierSettleDataResp Settle = 15;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.Action_.settle_), _Internal::kOneofCaseOffset + 0, 11, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes NextPackage = 2047;
    {PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.nextpackage_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::SoldierCase>()},
      {::_pbi::TcParser::GetTable<::proto::ChangeInfo>()},
      {::_pbi::TcParser::GetTable<::proto::SoldierNodeData>()},
      {::_pbi::TcParser::GetTable<::proto::SoldierSyncData>()},
      {::_pbi::TcParser::GetTable<::proto::SoldierEffect>()},
      {::_pbi::TcParser::GetTable<::proto::InteractShopResp>()},
      {::_pbi::TcParser::GetTable<::proto::InteractSoldierBattleResp>()},
      {::_pbi::TcParser::GetTable<::proto::InteractSoldierSelectResp>()},
      {::_pbi::TcParser::GetTable<::proto::InteractEventSettlementOfDisputeResp>()},
      {::_pbi::TcParser::GetTable<::proto::InteractEventSettlementOfDisputeBattleResp>()},
      {::_pbi::TcParser::GetTable<::proto::Nil>()},
      {::_pbi::TcParser::GetTable<::proto::SoldierSettleDataResp>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SoldierInteractResp::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SoldierInteractResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.cases_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.effects_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.nextpackage_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.change_ != nullptr);
      _impl_.change_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.node_ != nullptr);
      _impl_.node_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.syncdata_ != nullptr);
      _impl_.syncdata_->Clear();
    }
  }
  _impl_.id_ = 0u;
  clear_Action();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SoldierInteractResp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SoldierInteractResp& this_ = static_cast<const SoldierInteractResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SoldierInteractResp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SoldierInteractResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.SoldierInteractResp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 Id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_id(), target);
    }
  }

  // repeated .proto.SoldierCase Cases = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_cases_size());
         i < n; i++) {
      const auto& repfield = this_._internal_cases().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // .proto.ChangeInfo Change = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.change_, this_._impl_.change_->GetCachedSize(), target,
        stream);
  }

  // .proto.SoldierNodeData Node = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.node_, this_._impl_.node_->GetCachedSize(), target,
        stream);
  }

  // .proto.SoldierSyncData SyncData = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.syncdata_, this_._impl_.syncdata_->GetCachedSize(), target,
        stream);
  }

  // repeated .proto.SoldierEffect Effects = 6;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_effects_size());
         i < n; i++) {
      const auto& repfield = this_._internal_effects().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              6, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  switch (this_.Action_case()) {
    case kShopResp: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          8, *this_._impl_.Action_.shopresp_, this_._impl_.Action_.shopresp_->GetCachedSize(), target,
          stream);
      break;
    }
    case kBattleResp: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          9, *this_._impl_.Action_.battleresp_, this_._impl_.Action_.battleresp_->GetCachedSize(), target,
          stream);
      break;
    }
    case kSelectResp: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          10, *this_._impl_.Action_.selectresp_, this_._impl_.Action_.selectresp_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEventSettlementOfDisputeResp: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          11, *this_._impl_.Action_.eventsettlementofdisputeresp_, this_._impl_.Action_.eventsettlementofdisputeresp_->GetCachedSize(), target,
          stream);
      break;
    }
    case kEventSettlementOfDisputeBattleResp: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          12, *this_._impl_.Action_.eventsettlementofdisputebattleresp_, this_._impl_.Action_.eventsettlementofdisputebattleresp_->GetCachedSize(), target,
          stream);
      break;
    }
    case kNilResp: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          14, *this_._impl_.Action_.nilresp_, this_._impl_.Action_.nilresp_->GetCachedSize(), target,
          stream);
      break;
    }
    case kSettle: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          15, *this_._impl_.Action_.settle_, this_._impl_.Action_.settle_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  // bytes NextPackage = 2047;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_nextpackage().empty()) {
      const ::std::string& _s = this_._internal_nextpackage();
      target = stream->WriteBytesMaybeAliased(2047, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SoldierInteractResp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SoldierInteractResp::ByteSizeLong(const MessageLite& base) {
  const SoldierInteractResp& this_ = static_cast<const SoldierInteractResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SoldierInteractResp::ByteSizeLong() const {
  const SoldierInteractResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SoldierInteractResp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // repeated .proto.SoldierCase Cases = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_cases_size();
      for (const auto& msg : this_._internal_cases()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .proto.SoldierEffect Effects = 6;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_effects_size();
      for (const auto& msg : this_._internal_effects()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // bytes NextPackage = 2047;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_nextpackage().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_nextpackage());
      }
    }
    // .proto.ChangeInfo Change = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.change_);
    }
    // .proto.SoldierNodeData Node = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.node_);
    }
    // .proto.SoldierSyncData SyncData = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.syncdata_);
    }
    // uint32 Id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_id());
      }
    }
  }
  switch (this_.Action_case()) {
    // .proto.InteractShopResp ShopResp = 8;
    case kShopResp: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.shopresp_);
      break;
    }
    // .proto.InteractSoldierBattleResp BattleResp = 9;
    case kBattleResp: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.battleresp_);
      break;
    }
    // .proto.InteractSoldierSelectResp SelectResp = 10;
    case kSelectResp: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.selectresp_);
      break;
    }
    // .proto.InteractEventSettlementOfDisputeResp EventSettlementOfDisputeResp = 11;
    case kEventSettlementOfDisputeResp: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.eventsettlementofdisputeresp_);
      break;
    }
    // .proto.InteractEventSettlementOfDisputeBattleResp EventSettlementOfDisputeBattleResp = 12;
    case kEventSettlementOfDisputeBattleResp: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.eventsettlementofdisputebattleresp_);
      break;
    }
    // .proto.Nil NilResp = 14;
    case kNilResp: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.nilresp_);
      break;
    }
    // .proto.SoldierSettleDataResp Settle = 15;
    case kSettle: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.Action_.settle_);
      break;
    }
    case ACTION_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SoldierInteractResp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SoldierInteractResp*>(&to_msg);
  auto& from = static_cast<const SoldierInteractResp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SoldierInteractResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_cases()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_cases());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_effects()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_effects());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_nextpackage().empty()) {
        _this->_internal_set_nextpackage(from._internal_nextpackage());
      } else {
        if (_this->_impl_.nextpackage_.IsDefault()) {
          _this->_internal_set_nextpackage("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.change_ != nullptr);
      if (_this->_impl_.change_ == nullptr) {
        _this->_impl_.change_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.change_);
      } else {
        _this->_impl_.change_->MergeFrom(*from._impl_.change_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.node_ != nullptr);
      if (_this->_impl_.node_ == nullptr) {
        _this->_impl_.node_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.node_);
      } else {
        _this->_impl_.node_->MergeFrom(*from._impl_.node_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.syncdata_ != nullptr);
      if (_this->_impl_.syncdata_ == nullptr) {
        _this->_impl_.syncdata_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.syncdata_);
      } else {
        _this->_impl_.syncdata_->MergeFrom(*from._impl_.syncdata_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_Action();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kShopResp: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.shopresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.shopresp_);
        } else {
          _this->_impl_.Action_.shopresp_->MergeFrom(*from._impl_.Action_.shopresp_);
        }
        break;
      }
      case kBattleResp: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.battleresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.battleresp_);
        } else {
          _this->_impl_.Action_.battleresp_->MergeFrom(*from._impl_.Action_.battleresp_);
        }
        break;
      }
      case kSelectResp: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.selectresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.selectresp_);
        } else {
          _this->_impl_.Action_.selectresp_->MergeFrom(*from._impl_.Action_.selectresp_);
        }
        break;
      }
      case kEventSettlementOfDisputeResp: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.eventsettlementofdisputeresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.eventsettlementofdisputeresp_);
        } else {
          _this->_impl_.Action_.eventsettlementofdisputeresp_->MergeFrom(*from._impl_.Action_.eventsettlementofdisputeresp_);
        }
        break;
      }
      case kEventSettlementOfDisputeBattleResp: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.eventsettlementofdisputebattleresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.eventsettlementofdisputebattleresp_);
        } else {
          _this->_impl_.Action_.eventsettlementofdisputebattleresp_->MergeFrom(*from._impl_.Action_.eventsettlementofdisputebattleresp_);
        }
        break;
      }
      case kNilResp: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.nilresp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.nilresp_);
        } else {
          _this->_impl_.Action_.nilresp_->MergeFrom(*from._impl_.Action_.nilresp_);
        }
        break;
      }
      case kSettle: {
        if (oneof_needs_init) {
          _this->_impl_.Action_.settle_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.Action_.settle_);
        } else {
          _this->_impl_.Action_.settle_->MergeFrom(*from._impl_.Action_.settle_);
        }
        break;
      }
      case ACTION_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SoldierInteractResp::CopyFrom(const SoldierInteractResp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.SoldierInteractResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SoldierInteractResp::InternalSwap(SoldierInteractResp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.cases_.InternalSwap(&other->_impl_.cases_);
  _impl_.effects_.InternalSwap(&other->_impl_.effects_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nextpackage_, &other->_impl_.nextpackage_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.id_)
      + sizeof(SoldierInteractResp::_impl_.id_)
      - PROTOBUF_FIELD_OFFSET(SoldierInteractResp, _impl_.change_)>(
          reinterpret_cast<char*>(&_impl_.change_),
          reinterpret_cast<char*>(&other->_impl_.change_));
  swap(_impl_.Action_, other->_impl_.Action_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata SoldierInteractResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_soldier_5finteract_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
